### ISSUE TITLE
Download: "No streams available"!?

### ISSUE THREAD

**Issue by Enkidu70** [TeamNewPipe/NewPipe#11252]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Open https://www.youtube.com/watch?v=5rCUTVWJ1Po
2. Select Download
👉 "No streams available".

### Expected behavior

At least, I should be able to download the stream that is currently played.

### Actual behavior

NewPipe tells me, no streams available for download.

### Screenshots/Screen recordings

_none_

### Affected Android/Custom ROM version

Android 14

### Affected device model

OnePlus 8T

**Comment by AudricV** [comment]
This is currently an ended livestream which is in the post live state.

Support of downloading these livestreams is not implemented yet.

You can wait until YouTube reencode the VOD as a regular one.

**Comment by Enkidu70** [comment]
> This is currently an ended livestream which is in the post live state.

Thank you for explanation. How can I see this state in NewPipe? (Because it is my default app for YT and it would be some work to open it in a different app.)

> Support of downloading these livestreams is not implemented yet.

:(
 
> You can wait until YouTube reencode the VOD as a regular one.

No problem. This leads me to my question above. :)

**Comment by Feuerswut** [comment]
fixed in 27.1

**Comment by AudricV** [comment]
> How can I see this state in NewPipe? (Because it is my default app for YT and it would be some work to open it in a different app.)

You can see it with the toast `No streams available` when trying to download videos in this state.

**Comment by Feuerswut** [comment]
![Screenshot_20240714-211918.png](https://github.com/user-attachments/assets/8281481b-aa24-48b0-a5e0-54f508d2962d)

it is not an issue in the 0.27.1 version.

**Comment by wb9688** [comment]
@Feuerswut: This is only an issue when the livestream has just ended. After some time, YouTube changes it to a normal video and then the video is playable again in NewPipe. Since it has now been 5 days ago, that has already happened with this video and you can play it again, however this issue isn't fixed in NewPipe v0.27.1. It also seems like you use a fork of NewPipe, which we don't support here.

**Comment by Feuerswut** [comment]
> @Feuerswut: This is only an issue when the livestream has just ended. After some time, YouTube changes it to a normal video and then the video is playable again in NewPipe. Since it has now been 5 days ago, that has already happened with this video and you can play it again, however this issue isn't fixed in NewPipe v0.27.1. It also seems like you use a fork of NewPipe, which we don't support here.

livestreams and premieres cannot and never were able go be downloaded by newpipe. so this is not a bug, its a feature request, which cannot be serviced atm

**Comment by ShareASmile** [comment]
> livestreams and premieres cannot and never were able to be downloaded by newpipe. so this is not a bug, its a feature request.

There are issues open for that,  you can search and upvote them.
