### ISSUE TITLE
v0.15.0 playback audio unsync

### ISSUE THREAD

**Issue by beskhu3epnm** [TeamNewPipe/NewPipe#2039]
There is a problem with downloading videos with the new version of NewPipe. When you open the video in a video player like MX Player or QuickPic for example, scrubbing through the video at any time heavily de-synchronizes the audio or mutes it completely. This means for me that downloading videos with NewPipe is completely useless to me! If I have a 2 hour video, and I want to advance 30 minutes into it, the audio will not be present or be completely out of sync. Transferring the videos onto a PC, it does play fine in mpv. Transferring back to the smartphone however, the problem remains.

Using Android 8.1.0 on the Redmi Note 5. I have not encountered this issue before with any other downloader. The video players are up-to-date.

**Comment by theScrabi** [comment]
Try downloading 360p or 720p that should work

**Comment by beskhu3epnm** [comment]
@theScrabi Indeed 360p and 720p does work. But you have to understand that my patience for the muxing feature is all but shot at this point. It adds greater insult to injury when it appears that finally it has been implemented after waiting for such a long time, only for it to be unusable. I hope to God this gets fixed within a month or two. I thought finally today I could abandon Videoder as my go-to YouTube downloader, which I use all the time.

**Comment by TGWGitHub** [comment]
I have the same issue here as well on both my devices, one is Samsung running Android 6.0.1, and the other is Nokia running Android 8.1.0.

Hope this can be fixed soon, it's a most wanted functionality.

**Comment by FaizKhan5** [comment]
@beskhu3epnm Use MX Player with HW+ or SW

**Comment by beskhu3epnm** [comment]
@FaizKhan5 Thank you.

**Comment by FaizKhan5** [comment]
@theScrabi https://github.com/TeamNewPipe/NewPipe/pull/1944#issuecomment-454238801

**Comment by TGWGitHub** [comment]
@FaizKhan5

Tried every setting, same problem unfortunately...

Thanks though

**Comment by FaizKhan5** [comment]
@TGWGitHub Try NOVA Player from playstore.

**Comment by kapodamy** [comment]
@theScrabi fixed in https://github.com/TeamNewPipe/NewPipe/pull/1944/commits/167ad32bfe0d3ff333f17f90adfa129195636c1f (https://github.com/TeamNewPipe/NewPipe/pull/1944)

**Comment by theScrabi** [comment]
Awesome :)

**Comment by theScrabi** [comment]
[NewPipe-v0.15.1_fixed_download_preview.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/2787063/NewPipe-v0.15.1_fixed_download_preview.apk.zip)

**Comment by TGWGitHub** [comment]
@theScrabi

Tested v0.15.1, tried to download a 1080 videi, the video gets downloaded normally but without audio, Newpipe queue still shows the download in-queue (post-processing) and never finishes, screenshot:

https://i.postimg.cc/6Q2qCm5G/Screenshot-2019-01-23-13-58-41-1.png

**Comment by theScrabi** [comment]
@TGWGitHub I can not confirm sorry.

**Comment by TGWGitHub** [comment]
@theScrabi

Tested on my other phone (Nokia running Android 8.1.0) and it worked fine.

I wonder why it's not working on my Samsung (Android 6.0.1).. is there a way I can send debug logs or something?

**Comment by TGWGitHub** [comment]
Alright, I'll try and see if u can get to know how to use Logcat for this purpose, don't have a computer handy at this time to use Android Studio.

Thanks.

**Comment by TGWGitHub** [comment]
Seems I need a computer to be able to do anything useful...

**Comment by FaizKhan5** [comment]
For mine it works perfectly on 8.0.0
