### ISSUE TITLE
Background player stops responding after disconnecting from car bluetooth

### ISSUE THREAD

**Issue by Makaque** [TeamNewPipe/NewPipe#2397]
- [X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

If I shut my vehicle off while streaming youtube over bluetooth on the background player, the media stream can no longer be played. The app doesn't crash, and I can navigate, but I cannot resume play on the background player. Tapping play does nothing. Skipping forward or back in a playlist causes it to move to the next or previous item as expected, but does not begin to play, and tapping play still does not work. Tapping along the media progress slider to attempt to force it to load causes the progress indicator to flash and move forward slightly, then return to the beginning, simultaneously a small black rectangle appears momentarily above the play button. 

Sometimes if I shut my car off only briefly, then turn it back on, media will resume play, suggesting the failure happens over some time.

**Comment by gkeegan** [comment]
Try attempting to do this with something like Spotify or any other music streaming app and report results please. Some info about your device might also be helpful.

**Comment by Makaque** [comment]
Tried with Spotify. Played playlist in car, and shut car off in the middle of the song. After 20 minutes I pressed play and playback resumed as normal. 

My phone is a Xiaomi redmi note 4x (mido). 

Additional details. The Newpipe app continues to function after playback stops working. I don't need to kill the whole app to get it to begin working again, I only need to close the background player, then select background play again.

**Comment by Redirion** [comment]
this might be related to the first issue described in #1989.
I have noticed it too.

**Comment by Fusseldieb** [comment]
Yes, confirmed. Also happens on my car. 

I shut it off, the player itself pauses and the control freeze. I cannot resume playback, the controls do nothing and it only works again if I press "X" on the notification and open a new song/playlist. 

Other apps handle that fine

**Comment by Skylead** [comment]
This bug isn't limited to background player, it's breaking main player too when the car is shutoff and the phone loses bluetooth connection. I can do more testing to confirm it in the popup player as well. All playback will fail as will reselecting the same video. Can be fixed by loading a different video and then returning to the original content.

**Comment by Skylead** [comment]
Update, pausing the video before shutting off the car doesn't help it hold onto the stream. However, disabling bluetooth from the phone before shutting off the car keeps everything working without reloading the video. Maybe a lost bluetooth connection isn't being handled properly?

**Comment by Redirion** [comment]
reading the [release notes](https://github.com/google/ExoPlayer/blob/dev-v2-r2.11.5/RELEASENOTES.md) of the upcoming ExoPlayer 2.11.5 I have found something interesting:
`MediaSession extension:

    Only set the playback state to BUFFERING if playWhenReady is true`

This is a trivial fix done in this [commit](https://github.com/google/ExoPlayer/pull/7367).

I wonder if this is the cause for the issue, the state might always be in "BUFFERING" instead of "PAUSED", so that when on resuming later the media source is not refreshed properly even though it should, leaving to an endless seek on an invalid source.

**Comment by Skylead** [comment]
ExoPlayer patched apk doesn't seem to have changed this bug behavior for me

**Comment by stiw47** [comment]
I can confirm everything what OP said.
My phones are Mi 6 custom ROM Havoc OS Pie and Samsung S9 Duos latest stock Q firmware
Whatever player is working, video or background, it will not continue or be responsive after car turn off. Also, all other streaming apps, Spotify for example, will continue playback on car bluetooth reconnecting.

**Comment by Stypox** [comment]
Is this fixed in the apk provided in #3178?

**Comment by Redirion** [comment]
Initial testing shows indeed that this problem might have been resolved! @Stypox

**Comment by Stypox** [comment]
Great! Let's close this now, since #3178 will be merged surely

**Comment by opusforlife2** [comment]
> will be merged surely

Dear god I don't even want to imagine the possibility that it won't. :|

**Comment by Makaque** [comment]
I'm still experiencing this issue with the apk provided in #3178.

**Comment by Redirion** [comment]
For me the issue still appears to be resolved with the test apk from pr #3178 

Can anyone else give feedback?

**Comment by opusforlife2** [comment]
@Makaque Could you try the latest debug apk? You can find it from the pinned issue.

**Comment by opusforlife2** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/4355#issuecomment-701015687

**Comment by Flashwalker** [comment]
I have the same problem. The player suddenly stops and hangs with an endless preloading cycle.

**Comment by Stypox** [comment]
@Flashwalker the specific issue you are having, i.e. stopping suddenly during playback, may be fixed by 0.20.3. Could you test the RC in the pinned issue?

**Comment by Flashwalker** [comment]
@Stypox It got even worse.   Stream is lost more often than in the previous version. I have 2 versions installed.

**Comment by Stypox** [comment]
@Flashwalker currently there is an issue when there are multiple versions installed, try to keep installed only the latest one (0.20.6)

**Comment by mzhubail** [comment]
@opusforlife2 @Stypox

I'm affected by the same issue, but I'm not familiar with native android development.  How can I get around to tackling it?  see logs, use debug apk?

**Comment by Stypox** [comment]
@mzhubail I think you start the debug APK via Android Studio and try to understand what happens while in debug mode. If debug mode does not work or is too complicated too use, you can also add `Log.e(TAG, "...")` calls around and do print-debugging.

**Comment by kaitlynia** [comment]
Still an issue in 2025. I'm a delivery driver and I'm constantly getting in and out of my car. When I want to listen to music, I have to avoid "full album" uploads because NewPipe "forgets" the seek position randomly when resuming the BT connection, or the media controls just fail to respond and refocusing the app restarts the video from the beginning, essentially causing the same problem since I'll eventually want to change what I'm listening to. It does not always happen, which is even more frustrating for repro's sake, so I guess this is why this bug is ancient at this point.

**Comment by Skylead** [comment]
Yeah still an issue, though I stopped commenting on it.

A change from before is pausing playback before turning off vehicle does usually keep if from messing up. If I forget though usually the app can't recover playing that item (or loses the whole playlist) until I force quit the app and relaunch it. (This also happens with forks like PipePipe)

Happens on both my vehicles, 2017 Outback and 2012 Camry. I'm currently running a Pixel 4a with GrapheneOS
