### ISSUE TITLE
Non Authorized Apps Captcha Verification

### ISSUE THREAD

**Issue by mehedihasanziku** [TeamNewPipe/NewPipe#3134]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

![Screenshot_2020-02-23-19-02-26](https://user-images.githubusercontent.com/48652123/75112584-63909600-566f-11ea-880b-4b275e49b3c8.png)

I know it's a very old issue, maybe you are guys working on it, i can see now you guys added done (tik) button. This button goes back to video startup list. That's good, before it was stuck at white screen. But why this captcha behaving like that and why non-authorized issue continuosly appearing even after completing captcha.

I am now using latest version.

Let me know how to deal with it

**Comment by wb9688** [comment]
What version of NewPipe are you using? This issue should be fixed in v0.18.4.

**Comment by mehedihasanziku** [comment]
[
![Screenshot_2020-02-23-19-26-09](https://user-images.githubusercontent.com/48652123/75112864-722c7c80-5672-11ea-9c44-1990fa0d5df9.png)
](url)

You can see. It should be fixed.

**Comment by Stypox** [comment]
Have you solved the captcha and clicked Submit, before tapping the Done button?

**Comment by mehedihasanziku** [comment]
> Have you solved the captcha and clicked Submit, before tapping the Done button?

Yes, Solved Captcha > Submit > Done.

But I am now closing this thread, because captch issue resolved automatically, i will re-open this thread if it appears again.

**Comment by mehedihasanziku** [comment]
Just tired with this issue, i got this after closing this thread but it was cleared after solving and ticking done, but it was cleared almost after 5min. 

Now i can see it's still appearing & appearing from last night 

Solved Captcha
![Screenshot_2020-02-26-10-19-43](https://user-images.githubusercontent.com/48652123/75311736-f56fed00-5881-11ea-9bf7-fa29b9859bf8.png)

After Submit
![Screenshot_2020-02-26-10-19-49](https://user-images.githubusercontent.com/48652123/75311764-06b8f980-5882-11ea-9459-f02e4b626853.png)


After ticking done, nothing happened, captcha will kill me 😪😪

**Comment by Stypox** [comment]
@mehedihasanziku 
Could you test this APK (from #3035)? It does not fix the bug, but enables me to gather more information. When you press :heavy_check_mark (after solving) it throws an error on purpose (so that I can see the content of cookies): please paste the bug report content here.
[app-debug_2.zip](https://github.com/TeamNewPipe/NewPipe/files/4142983/app-debug_2.zip)

**Comment by KonoromiHimaries** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/3136

**Comment by mehedihasanziku** [comment]
Just used your 2nd uploaded appdebug apk.

Post one not throwing an eror. 

Because we can copy json data with markdown format  now i can see this feature is missing in app and also mark down link also saying parse eror, i am not sure what is happening.

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe.debug",
   "version": "0.18.2",
   "os": "Linux Android 6.0 - 23",
   "time": "2020-02-27 05:10",
   "exceptions": [
      "java.lang.NullPointerException: Found cookies: GPS=1; s_gl=e3ea30620a3c9e68880a30237b86c6cfcwIAAABHQg==; CONSENT=WP.28408e; GPS=1; s_gl=e3ea30620a3c9e68880a30237b86c6cfcwIAAABHQg==; CONSENT=WP.28408e; GPS=1; s_gl=e3ea30620a3c9e68880a30237b86c6cfcwIAAABHQg==; CONSENT=WP.28408e; GPS=1; s_gl=e3ea30620a3c9e68880a30237b86c6cfcwIAAABHQg==; CONSENT=WP.28408e\n\tat org.schabi.newpipe.ReCaptchaActivity.saveCookiesAndFinish(ReCaptchaActivity.java:134)\n\tat org.schabi.newpipe.ReCaptchaActivity.onOptionsItemSelected(ReCaptchaActivity.java:121)\n\tat android.app.Activity.onMenuItemSelected(Activity.java:2951)\n\tat androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)\n\tat androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)\n\tat androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)\n\tat androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)\n\tat androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)\n\tat androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)\n\tat androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)\n\tat androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)\n\tat androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)\n\tat androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)\n\tat androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)\n\tat androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)\n\tat androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)\n\tat android.view.View.performClick(View.java:5265)\n\tat android.view.View$PerformClick.run(View.java:21534)\n\tat android.os.Handler.handleCallback(Handler.java:815)\n\tat android.os.Handler.dispatchMessage(Handler.java:104)\n\tat android.os.Looper.loop(Looper.java:207)\n\tat android.app.ActivityThread.main(ActivityThread.java:5788)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)\n\tat de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)\n"
   ],
   "user_comment": ""
}


Just Installed Latest Version of newpipe, this version showing only 3videos on startup list, is it bug?

**Comment by Stypox** [comment]
@mehedihasanziku strange, unfortunately I am not able to debug the issue since with the cookies in the bug report the ReCaptcha activity should work, sorry. I will try to fix this if it happens to me and I can debug with more tools.

> Just Installed Latest Version of newpipe, this version showing only 3videos on startup list, is it bug?

Yeah, see #3145

**Comment by mehedihasanziku** [comment]
Thanks.

**Comment by baraa272** [comment]
A permanent FIX for this is to change your country to North America 
Europe region sometimes get recaptcha but NA doesnt get any so FAR

**Comment by Stypox** [comment]
Another crash report from a user on Telegram. It seems like there is another cookie type, since these found cookies are completely different from the other ones. https://del.dog/icykimohea.txt
`NID=201=vuhpUOzyLo88J6Ikxa3paF5FSSdmDHdDGvNqovDv2-FE2lDQiNCHUN2naF08SFo1dGmdlMmQ2SnHDnW0uPpePUQd1pZ_4IwqBEL7wvfP6pasPuLmoNTBv6PrNP-jtzct9YhVwPX1UIZjQSKNAT0o82pPu7kH6Qpg7k6hnIdu4A8`

**Comment by Stypox** [comment]
@mehedihasanziku Could you try this apk? I don't think it will solve the issue for you (it hopefully will for other people), but who knows ;-)
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4460508/app-debug.zip)

**Comment by mehedihasanziku** [comment]
> @mehedihasanziku Could you try this apk? I don't think it will solve the issue for you (it hopefully will for other people), but who knows ;-)
> [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4460508/app-debug.zip)

I can try, but i am not facing this issue anymore, it will help?

Or should i report once i face again?

**Comment by Stypox** [comment]
No, there is no need then, thank you anyway. Also, that apk is now out of date, I already got more info onto which investigate.

**Comment by mehedihasanziku** [comment]
Captcha Page Not loading, Showing Blank Screen With Top Bar, Is it bug or my network issue?

**Comment by Stypox** [comment]
Are you using the latest apk provided in #3414? Answer me there, to keep all of the discussion in one place, please. Anyway, this could be a network issue

**Comment by mehedihasanziku** [comment]
![Screenshot_2020-07-06-15-27-08](https://user-images.githubusercontent.com/48652123/86578221-482e8380-bf9d-11ea-8d29-71d9028978a8.png)

Again white page, no captcha page loading at all. Please check this issue

**Comment by Stypox** [comment]
This can not be solved unfortunately, I don't know why Google is not displaying a captcha

**Comment by mehedihasanziku** [comment]
Now i can see double layer captcha, first one not visible like above, then if i press back a new captcha appear, but it's not save that cookie like before, so it's like before bug
![Screenshot_2020-07-10-14-22-38](https://user-images.githubusercontent.com/48652123/87134238-3d842f00-c2ba-11ea-9cc5-850b11ca3f2c.png)
![Screenshot_2020-07-10-14-24-00](https://user-images.githubusercontent.com/48652123/87134266-4543d380-c2ba-11ea-926d-fe62cae869a8.png)


is it possible to store second captcha cookie to work fine like old one?

**Comment by Stypox** [comment]
Could you capture the logcat of what happens using adb (or Android Studio's tool) and running the debug apk from release 0.19.3: ([NewPipe_v0.19.3_RC4.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4570250/NewPipe_v0.19.3_RC4.apk.zip) taken from #3479)?

**Comment by mehedihasanziku** [comment]
After two days i am facing again this bug.

Installed "Matlog" apk, to see logcat, i am adding "newpipe" keyword filter screenshot, let me know if you need logcat file too.

![Screenshot_2020-07-13-21-25-40](https://user-images.githubusercontent.com/48652123/87322937-e4352d80-c54f-11ea-985f-826357411984.png)

**Comment by Stypox** [comment]
@mehedihasanziku the logcat should be hundreds or even thousands of lines long. Idk why there is only one line there, maybe debug logging is disabled on your phone (some manufacturers do this to improve performance)

**Comment by wb9688** [comment]
@Stypox: It's because filtering by "newpipe" won't work as not everything includes "newpipe". You need to filter by the process ID of that NewPipe instance.

**Comment by mehedihasanziku** [comment]
> @mehedihasanziku the logcat should be hundreds or even thousands of lines long. Idk why there is only one line there, maybe debug logging is disabled on your phone (some manufacturers do this to improve performance)

i already meantioned the reason, i filtered the logcat file using "newpipe" keyword & found only this one. let me know if i can help you more better way.

**Comment by wb9688** [comment]
@mehedihasanziku: Yes, like I said you need to filter by the process ID.
