### ISSUE TITLE
System UI keeps stopping [Image Loader issue]

### ISSUE THREAD

**Issue by gulachev** [TeamNewPipe/NewPipe#4638]
### Checklist

- [x] I am using the latest version - 0.20.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Search the concerned video like 'Hello World'.
2. Enqueue in the background
3. Open the video. 
(Both the cases 2. and 3. produce the similar behaviour)

### Actual behaviour
The video or audio(when playing in background) starts playing, the screen starts flickering , in the sense that display gets on and off , flickers for some time displaying the messege -- 'System UI keeps stopping' (giving two options -- app info or close app). The app gets closed for the latter option, but if pressed anywhere else on the screen the video plays continuosly with audio, screen flickering for some time and then phone gets restarted.

### Expected behavior

The video to be played till the end.

### Screenshots/Screen recordings

![Screenshot_20201025-053028](https://user-images.githubusercontent.com/73409058/97095970-5dffab80-1655-11eb-8c3f-a6899094d436.png)

### Logs
 None

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Motorola One Power (P30 Note)

**Comment by k3a** [comment]
Related logcat logs https://pastebin.com/raw/c65CcAyN

**Comment by Sekitan** [comment]
Same here, same issue with my Sony Xperia XZ2 Compact...

**Comment by UserX404** [comment]
@k3a 
- Do you encouter the same behavior as described here?
https://github.com/TeamNewPipe/NewPipe/issues/4644#issuecomment-716726661

**Comment by k3a** [comment]
I think it may be the same problem. But in my case, I was using normal player (no background one). The app opened fine, allowed me to search a query. Clicking on a search result started playing the video but soon after System UI would crash, forcing the lock screen to appear. As I have fingerprint unlocking I was able to unlock, then after a second or two, System UI would crash again and so on until I force-closed NewPipe from the multitask switcher quickly. After hour or so I tried to open NewPipe again and the same thing would happen, suggesting it is a bug. Then I found this github issue.

But today (1 day after), I tried opening NewPipe now to-recheck and it appears to be working and playing normally so I don't get it. I don't remember restarting the phone or updating the app yet now it magically works again for me, it seems. Maybe something has changed on youtube side? Does it still crash System UI for you? I will test it again later and report if it starts doing that for me again.

**Comment by k3a** [comment]
EDIT: It does not crash for me for some videos but it crashes for me for "Queen - I Want to Break Free (Official Video)" as in the issue description. Maybe it is related to DRM or some special stream types?

**Comment by UserX404** [comment]
Because i have a ~10digit unlock code the imeis to short to kill the app. It sounds like the same bug and i also noticed that some links ar working and others result into locking.
Crashing example link: https://www.youtube.com/watch?v=bwmSjveL3Lc

**Comment by gulachev** [comment]
> Because i have a ~10digit unlock code the time is to short to kill the app. It sounds like the same bug and i also noticed that some links are working and others result into locking.
> Crashing example link: https://www.youtube.com/watch?v=bwmSjveL3Lc
> Working example link:
> https://www.youtube.com/watch?v=dISNgvVpWlo

If your phone gets restarted or shut off then it's the same problem.

**Comment by nonremittal** [comment]
Any word on this?

Crashes my phone on some videos, sometimes restarts in a terminal mode.

Would love if we could just disable the new UI, 0.19 was perfect but sadly it doesn't work any more.

(Xiaomi MI A2, Android 10).

**Comment by k3a** [comment]
FYI happens still in 0.20.2 version installed from the release apk.

I can confirm the crashing and working links of @UserX404 but also simply the Queen mentioned in the issue description causes the SystemUI crash.

None of the links crash and all play ok under lineage-17.1-20201021 on Xperia XZ2 (also Android 10; custom ROM).

Looks like the bug is triggered only for some SystemUI builds (some ROMs only). But it's pity it happens under the official Xperia XZ2c ROM and it doesn't happen under unofficial XZ2 (maybe also XZ2c, can't test) ROM :P .

[More adb logs](https://pastebin.com/raw/rYy9XD00)

**Comment by opusforlife2** [comment]
> None of the links crash and all play ok under lineage-17.1-20201021 on Xperia XZ2 (also Android 10; custom ROM).
Looks like the bug is triggered only for some SystemUI builds (some ROMs only). 

Thanks for confirming that.

**Comment by nonremittal** [comment]
Tested with UserX404's links, can confirm the first one crashes and the second one plays fine.

Not sure how to figure out what SystemUI build I have but the app info says Version 10.

**Comment by arielshulman** [comment]
Have MI A2 with original android one launcher as @nonremittal and can confirm it also crashes with 0.20.0-0.20.2 versions only for specific youtube on bg player.
As a workaround, I disable notifications on settings of the device for newpipe app. Then everything works (and music continues play) but I can not access queue playlist of the player because it can be accessed only from notification bar.

**Comment by opusforlife2** [comment]
> As a workaround, I disable notifications on settings of the device for newpipe app

Can everyone else try this workaround and comment whether it works?

**Comment by UserX404** [comment]
> Can everyone else try this workaround and comment whether it works?

Will test if 0.20.2 appear on FDroid. 0.20.1 could not decrypt links anymore.
```
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=Rgw5dQOyySc
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ de_AT
* __Service:__ YouTube
* __Version:__ 0.20.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.extractor.exceptions.ParsingException: YouTube did not provide player config even after three attempts
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:664)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

</details>
<hr>
```

**Comment by k3a** [comment]
I can confirm disabling "NewPipe Notification" notification category fixes this on my Xperia XZ2c with the official FW.

**Comment by opusforlife2** [comment]
@Stypox

**Comment by nonremittal** [comment]
Can confirm disabling notifications works for me too.

However as @arielshulman says, this means I can't access the background player queue. In fact, queueing doesn't work at all (it just stops playing after the first item, even if I add more).

**Comment by dboydor** [comment]
Same issue that people have above and can confirm disabling "NewPipe Notification" notification fixes this on my Xperia XZ2c as well.

**Comment by gulachev** [comment]
> Can confirm disabling notifications works for me too.
> 
> However as @arielshulman says, this means I can't access the background player queue. In fact, queueing doesn't work at all (it just stops playing after the first item, even if I add more).

Same.

**Comment by UserX404** [comment]
Can confirm.
Same here on XZ2c.

**Comment by pauseee** [comment]
Same behaviour on MI A2 with stock rom.

**Comment by astatine** [comment]
I have the same problem on my Mi A2 (fully updated) with the newest NewPipe v0.20.2. [This video](https://www.youtube.com/watch?v=sq5t-1R5a8g) consistently crashes System UI. I have to restart the phone, unless I am able to quickly fingerprint-unlock the phone and immediately pause the video before the next crash.

**Comment by nonremittal** [comment]
Has this been fixed in 0.20.2?

Pretty serious bug.

**Comment by arielshulman** [comment]
Well, I'm not really an Android developer, but this crashes drived me crazy so I've tried search for clues.
I've downloaded the Android Studio and tried debug the code directly on my phone.

I've managed to get from my phone logs the exception that crashes my systemui:
```
2020-11-14 21:10:17 system_app_crash (text, 2003 bytes)
Process: com.android.systemui
PID: 12456
UID: 10120
Flags: 0x30c83e0d
Package: com.android.systemui v29 (10)
Foreground: No
Build: xiaomi/jasmine/jasmine_sprout:10/QKQ1.190910.002/V11.0.15.0.QDIMIXM:user/release-keys

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalArgumentException: Bitmap is not valid
	at androidx.palette.graphics.Palette$Builder.<init>(Palette.java:611)
	at androidx.palette.graphics.Palette.from(Palette.java:103)
	at com.android.systemui.statusbar.notification.MediaNotificationProcessor.generateArtworkPaletteBuilder(MediaNotificationProcessor.java:307)
	at com.android.systemui.statusbar.notification.MediaNotificationProcessor.findBackgroundSwatch(MediaNotificationProcessor.java:251)
	at com.android.systemui.statusbar.MediaArtworkProcessor.processArtwork(MediaArtworkProcessor.kt:74)
	at com.android.systemui.statusbar.NotificationMediaManager.processArtwork(NotificationMediaManager.java:649)
	at com.android.systemui.statusbar.NotificationMediaManager.access$600(NotificationMediaManager.java:84)
	at com.android.systemui.statusbar.NotificationMediaManager$ProcessArtworkTask.doInBackground(NotificationMediaManager.java:679)
	at com.android.systemui.statusbar.NotificationMediaManager$ProcessArtworkTask.doInBackground(NotificationMediaManager.java:660)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```
As I saw it, I've searched in the code something related to thumbnail bitmap. I've found this:
https://github.com/TeamNewPipe/NewPipe/blob/c4a739bef66aaed3149595b7e4f4f38fde716961/app/src/main/java/org/schabi/newpipe/player/BasePlayer.java#L1460-L1465

so I've done this dummy change to the code:
``` Java
    @Nullable
    public Bitmap getThumbnail() {
        return BitmapFactory.decodeResource(context.getResources(), R.drawable.dummy_thumbnail);
    }
```

and for my surprise it worked, the app does not crash (and does not show a thumbnail on the notification bar ofcourse).

I hope this will lead a *real* developer to solve this issue 🤞

And if someone wants to validate by his phone that's this solves the crashing, here is an apk for my build:

> [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5541402/app-debug.zip)

**Comment by arielshulman** [comment]
I've tried to do some more research with my phone and got this quirk - 
Those examples of thumbnail images which cause the crash have the same width of 336px:
* [Image 1](https://i.ytimg.com/vi/bwmSjveL3Lc/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLC7UiS3MApFwGJcDJ-P3BBZujlCsQ)
* [Image 2](https://i.ytimg.com/vi/MCIaj-oLi28/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBh1WiqddAX_p0fZp-wdSNPljY7Ew)

Because they are less of the notification bar width size they won't be resized by this code:
https://github.com/TeamNewPipe/NewPipe/blob/c4a739bef66aaed3149595b7e4f4f38fde716961/app/src/main/java/org/schabi/newpipe/player/BasePlayer.java#L506-L511

I've tried to change the code and resize them, even by 1 pixel, aka:
``` Java
currentThumbnail = Bitmap.createScaledBitmap(loadedImage,
                (int) (width + 1),
                (int) (loadedImage.getHeight() / (loadedImage.getWidth() / width)), true);
```
everything worked fine and the image showed in the notification without crashing.

So I went one step further and tried set the new Bitmap back to the original dimensions, aka:
``` Java
currentThumbnail = Bitmap.createScaledBitmap(loadedImage,
                (int) (width + 1),
                (int) (loadedImage.getHeight() / (loadedImage.getWidth() / width)), true);
currentThumbnail = Bitmap.createScaledBitmap(currentThumbnail,
                (int) (width),
                (int) (loadedImage.getHeight() / (loadedImage.getWidth() / width)), true);
        
```
and it worked either... can't explain this madness. 
Hope you can 😄 and it helps getting solution.

**Comment by Stypox** [comment]
@ariel-lindemann thank you for the investigations! I tried to read up something about that and the documentation says that when the bitmap is not scaled it is returned as-is (i.e. the original one is returned). Probably the issue here is that `loadedImage` on some devices is discarded by the library we use to load thumbnails or by the garbage collector (even though it shouldn't) and thus becomes invalid. What we could do is create a new `BitMap` even if the wanted dimensions are equal to the original ones, thus preventing such a situation.

**Comment by arielshulman** [comment]
> @ariel-lindemann thank you for the investigations! I tried to read up something about that and the documentation says that when the bitmap is not scaled it is returned as-is (i.e. the original one is returned). Probably the issue here is that `loadedImage` on some devices is discarded by the library we use to load thumbnails or by the garbage collector (even though it shouldn't) and thus becomes invalid. What we could do is create a new `BitMap` even if the wanted dimensions are equal to the original ones, thus preventing such a situation.

Great. 
I played with this a little more and forced other thumbnails who didn't crashed the phone not to be resized also, but they still didn't crashed the phone, while the others I mention earlier still crashes the ui.

**Comment by UserX404** [comment]
Is this adressed in 0.20.3?
Can report that the issue still exists.

**Comment by opusforlife2** [comment]
> Can report that the issue still exists.

That's why it's still open. Someone has to open a PR with a fix along the lines of the investigation done above.

**Comment by arielshulman** [comment]
Just another little update.
I've managed to eliminate more options and focus where the crash really happens.

https://github.com/TeamNewPipe/NewPipe/blob/e274650956b54030c8fee76f24d46041ccbcb052/app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java#L104

If I comment that row, everything works fine even with the problematic images.
They even shows fine in the Notification as well.

Not sure yet what is the current solution though.

**Comment by Stypox** [comment]
@arielshulman thank you again! If you can find a way to detect such invalid bitmaps, as a workaround it would be enough to not put the album art into metadata, or maybe to force resizing the thumbnail to a pixel less/more, even though it wouldn't be a complete solution.

**Comment by arielshulman** [comment]
Can't manage to find the Bitmap unique feature that will identify the problematic images, but I can say that all of those I've seen where 336x188 size (but it's not a size issue, since a copy of the same img works perfectly), and they all have some special query parameter on their thumbnail URI which is seems to ask for this specific size of the images (as describe [here](https://stackoverflow.com/a/51203860/12578824)).

Anyway I've managed to workaround all of those by copying the image to another Bitmap and set it mutable and that works.
I've changed those lines:
https://github.com/TeamNewPipe/NewPipe/blob/d54c806e03fb665a1a47b9491707ca7275bfcc42/app/src/main/java/org/schabi/newpipe/player/BasePlayer.java#L505-L510

into:

``` Java
final Bitmap loadedImageCopy =
                loadedImage.copy(loadedImage.getConfig(),
                        true);
final float width = Math.min(
                context.getResources().getDimension(R.dimen.player_notification_thumbnail_width),
                loadedImage.getWidth());
currentThumbnail = Bitmap.createScaledBitmap(loadedImageCopy,
                (int) width,
                (int) (loadedImageCopy.getHeight() / (loadedImageCopy.getWidth() / width)), true);
```

As I said earlier, I'm not an Android/JAVA developer so I've no clue what is a reasonable workaround which will be efficient and won't cause other problems 🐞

**Comment by arielshulman** [comment]
Well, just checked last version, it doesn't fix the crash, but since it has an option to toggle the thumbnail on lockscreen it has an option to evade from crashing... 

![Screenshot_20201123-012653](https://user-images.githubusercontent.com/15850184/99920319-5baf7080-2d2b-11eb-919d-0b6adecc164e.png)

**Comment by dboydor** [comment]
Fantastic!  Turning that option off is good enough for me.  It works again.

**Comment by arielshulman** [comment]
> @ariel-lindemann thank you for the investigations! I tried to read up something about that and the documentation says that when the bitmap is not scaled it is returned as-is (i.e. the original one is returned). Probably the issue here is that `loadedImage` on some devices is discarded by the library we use to load thumbnails or by the garbage collector (even though it shouldn't) and thus becomes invalid. What we could do is create a new `BitMap` even if the wanted dimensions are equal to the original ones, thus preventing such a situation.


Tried basic change by moving only thumbnail loading from UIL into Glide and that seems to work fine -
``` Java
Glide.with(context)
                .asBitmap()
                .load(url)
                .into(this);
```

Instead of 

``` Java
ImageLoader.getInstance().resume();
ImageLoader.getInstance()
                .loadImage(url, ImageDisplayConstants.DISPLAY_THUMBNAIL_OPTIONS, this);
```

@Stypox It seems it could be UIL bug related issue as you suggested.

**Comment by Stypox** [comment]
The issue is not inside NewPipe but inside the UIL library: nostra13/Android-Universal-Image-Loader#908

**Comment by Stypox** [comment]
The issue is not inside NewPipe but inside the Universal Image Loader library: nostra13/Android-Universal-Image-Loader#908
Unfortunately the library is not being updated since 5 years, so I guess we can't wait for them to solve the issue. We should probably switch to Glide. @arielshulman thank you again for looking into this, and sorry for getting in touch so late. ;-)
