### ISSUE TITLE
Overlapping fonts

### ISSUE THREAD

**Issue by KatoriYuu** [TeamNewPipe/NewPipe#5096]
### Checklist

- [x] I am using the latest version - 0.20.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Use the largest font size in Android setting.

### Actual behaviour

Texts are overlapped.

### Expected behavior

Everything works correctly.

### Screenshots/Screen recordings

![Screenshot_20201204-202824](https://user-images.githubusercontent.com/42930110/101170643-55958a00-3671-11eb-9be2-5aae35d2ae19.png)

### Device info

 - Android version/Custom ROM version: Android 10, Stock ROM.
 - Device model: Nokia 8.1

**Comment by KatoriYuu** [comment]
The same issue was reported in the past. However it was caused by using a custom font. I think that the solution is displaying the  title of videos in only 1 line if the font size is too large. Another way is adding an option to customize the font size in app.

**Comment by wangear** [comment]
Hello! I'd like to work on this enhancement. Can i assigned to this issue? :)

**Comment by wangear** [comment]
I think that the solution is converting sp to dp.

**Comment by TiA4f8R** [comment]
> Can i assigned to this issue? :)
Done ;)

**Comment by TacoTheDank** [comment]
@wangear Could you provide a built debug APK with these changes so that @KatoriYuu can test them to see if it now works?

**Comment by TiA4f8R** [comment]
@TacoTheDank The CI is here for APKs: https://github.com/TeamNewPipe/NewPipe/suites/2249030764/artifacts/46755391

**Comment by wangear** [comment]
@TiA4f8R Thank you

**Comment by KatoriYuu** [comment]
@wangear Hi, I have tried the debug version. However, the problem with channels card still persists. I can see that your solution is hiding the view counter to make more space for title, which I think is not really convenient. Can you try to solve this in some other ways? I would prefer increasing the height of every card, or if it's not possible, I'm fine with displaying the title in one line, too.
![Screenshot_20210323-065154](https://user-images.githubusercontent.com/42930110/112073391-9674c880-8ba6-11eb-9a54-65e33215f886.png)

**Comment by wangear** [comment]
@KatoriYuu  the problem with channels card still persists -> Sorry. I'll fix it.
I can see that your solution is hiding the view counter to make more space for title ->
I checked the height of view and if each view overlapped (not word, just view), then I hide the count.
Because every Language has different height, so it is hard to check exactly.
I would prefer increasing the height of every card, or if it's not possible, I'm fine with displaying the title in one line, too.
-> I will think about it.
Thank you for advise.

**Comment by wangear** [comment]
@KatoriYuu 
How about this?
![Screenshot_20210323-103109_NewPipe Debug](https://user-images.githubusercontent.com/5685280/112079224-1c9f0800-8bc3-11eb-9f3b-312266bf8e3b.jpg)

I think that thumbnail position is better in the middle how about you?
any ideas?

**Comment by KatoriYuu** [comment]
@wangear Wow, that looks great. I agree with you, the thumbnail should be placed in the middle.

**Comment by wangear** [comment]
@KatoriYuu All right. Thank you.
