### ISSUE TITLE
"Show info" and "Video player" work the same for shared videos

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6500]
@sauravrao637 Thanks for your amazing contribution 😃.

As you may remember, #6371 is not fully resolved as stated in https://github.com/TeamNewPipe/NewPipe/pull/6385#issuecomment-850371381 . If you are free, please have a look at this issue.

Have a great day. Sorry for the pinge.

### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Unfortunately, 'Show info' is useless for videos. Videos tend to start according to 'Auto-play' setting. However, 'Video player' works the same. According to me, 'Show Info' should not start playback automatically.

### Expected behavior

This is how "Preferred 'Open' Setting" should work for shared videos.
Show info: Don't auto-play videos
Video player: Auto-lay videos on main player

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by SameenAhnaf** [comment]
@sauravrao637 Thanks for your amazing contribution 😃.

As you may remember, #6371 is not fully resolved as stated in #6385 (comment) . If you are free, please have a look at this issue.

Have a great day. Sorry for the pinge.

**Comment by rancidfrog** [comment]
It is not useless.
Since at them moment it is the only way to share new videos to queue.
Steps:
- Play video in background
- Share to newpipe
- select show info
-  long press background to enqueue

Without this there is no wayvtonshare to enqueue
So it is not useless at all, because show infobdoes not play video so it does not affect current queue

Until queue is handled via #5850 
Show info can be used as a workaround for queuing videos

**Comment by SameenAhnaf** [comment]
>This is how "Preferred 'Open' Action" should work for shared videos.
>Show info: Don't auto-play videos
>Video player: Auto-play videos on main player

Did you guys read the "Expected behaviour"? The reason why I am saying it useless is the fact that I knocked a couple of devs. Yet, the issue isn't still fixed now.

>Videos tend to start according to 'Auto-play' setting.

This is what happens unexpectedly. Watch the video for full explanation.

For first and second case, I enabled "Auto-play" but chose "Show info" and "Video info" . Video tends to auto-play in both cases.

The same goes for third and fourth cases. Video doesn't tend to play as "Auto-play" setting is "Never".

https://drive.google.com/file/d/12ZM8DqezvykcGHXttvka3dvoBxyoc9nC/view?usp=drivesdk

**Comment by sauravrao637** [comment]
> > This is how "Preferred 'Open' Action" should work for shared videos.
> > Show info: Don't auto-play videos
> > Video player: Auto-play videos on main player
> 
> Did you guys read the "Expected behaviour"? The reason why I am saying it useless is the fact that I knocked a couple of devs. Yet, the issue isn't still fixed now.
> 
> > Videos tend to start according to 'Auto-play' setting.
> 
> This is what happens unexpectedly. Watch the video for full explanation.
> 
> For first and second case, I enabled "Auto-play" but chose "Show info" and "Video info" . Video tends to auto-play in both cases.
> 
> The same goes for third and fourth cases. Video doesn't tend to play as "Auto-play" setting is "Never".
> 
> https://drive.google.com/file/d/12ZM8DqezvykcGHXttvka3dvoBxyoc9nC/view?usp=drivesdk

I get the real issue now.
By the way it might be the case settings are applied after the app restart, did u try that?

**Comment by SameenAhnaf** [comment]
@sauravrao637 I tried that way. The app still behaves the way as shown in the video.

Note that if "Video Player" open action and "Never" auto-play are selected, the app tends to show info of first video for channels and playlists. Personally, I'm in favour of this activity neither. Here are the reasons:
1. It's only helpful for description of first video.
2. There's no easy way to start playback directly (First tap to play, second to show interface, third to enter full screen)
3. There's no way to get back to the original channel or playlist.
That's why, I am in favour of these changes for channels and playlists.
Show info: Show info of channels or playlists.
Video player: Start playing all videos on main player.

>the video was real helpful, you may add this in the issue itself.

Yeah, I should have noticed that for avoiding argument. Sorry for the inconvenience. Also, thanks a bunch for reminding me to include.

**Comment by sauravrao637** [comment]
@SameenAhnaf To be honest to fix this issue one should me more than familiar with the NewPipe codebase, which (sadly) I'm still not, so will have to wait for some core member to fix this issue.

**Comment by Stypox** [comment]
Closing as now there is just one option again
