### ISSUE TITLE
Release 0.21.6

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#6577]
# APK for testing
From GitHub Actions: [NewPipe_v0.21.6_RC3.zip](https://github.com/TeamNewPipe/NewPipe/files/6760427/NewPipe_v0.21.6_RC3.zip)

**Please report _only new_ bugs** in this ticket. Corresponding PR: #6576 

# Changelogs 
### New
1- Long press on player share button to copy url to clipboard #6436
2- Added "Open website" button to WebView in license fragment #6314 
9- Recognize timestamps and hashtags in description #5523
10- Added manual tablet mode setting #6059 
11- Added ability to hide played items in a feed #3371 

### Improved
3- Support Storage Access Framework properly #5415 
4- Better error handling of terminated channels #5876 
5- Use constraint layout for play queue item #6443 
12- The Android share sheet for Android 10+ users now shows the content title and other improvements #5523
20- Update Invidious instances and support Piped links #6557

### Fixed
13- Dismiss choice dialog in onStop() to avoid a leaked window Exception: #6504
17- Don't enable SAF on Fire TV #6516 

### Development
6- Convert the abstract class DAOs to interfaces #5462 
7- Resolve Tabs style checks #6346 
8- Update Room to 2.3.0 #6313 
14- Replace the System.exit calls with getActivity.finishAffinity() #6495 
15- Update AndroidX Fragment to 1.3.4 #6394 
16- Annotate some overridden methods and parameters as NonNull #6528
18- Refactoring by Android Studio #6556
19- Comment out test-android CI job #6562
21- Ask for screenshots/video of UI changes in PR template #6539 

### New
1- Added `AccountTerminatedException` for terminated channels TeamNewPipe/NewPipeExtractor#580 
2- [SoundCloud] Added `streamPosition` for comments TeamNewPipe/NewPipeExtractor#625 

### Improved
9- Update Invidious instances and support Piped links TeamNewPipe/NewPipeExtractor#668

### Fixed
~~3-  [YouTube] Fix getting stream type of live streams TeamNewPipe/NewPipeExtractor#658~~
5- [SoundCloud] Update HARDCODED_CLIENT_ID TeamNewPipe/NewPipeExtractor#660
10- [YouTube] Fix extraction of age restricted videos TeamNewPipe/NewPipeExtractor#665

### Development
4- Add dependabot TeamNewPipe/NewPipeExtractor#552 
6-  Bump gson from 2.8.6 to 2.8.7 TeamNewPipe/NewPipeExtractor#654 
7- Bump rhino from 1.7.12 to 1.7.13 TeamNewPipe/NewPipeExtractor#656
8- Bump spotbugs-annotations from 4.0.2 to 4.2.3 TeamNewPipe/NewPipeExtractor#655

**Comment by SameenAhnaf** [comment]
1. Bookmarked playlists are not loading at all.

## Exception
* __User Action:__ bookmark
* __Request:__ Loading playlists
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Redmi/begonia/begonia:10/QP1A.190711.020/V12.0.7.0.QGGMIXM:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
	at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:502)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:74)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:486)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:438)
	at org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:435)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:131)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)
	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

2. Subscription feeds stop loading at the middle of process.
## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Redmi/begonia/begonia:10/QP1A.190711.020/V12.0.7.0.QGGMIXM:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
	at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:502)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:74)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:486)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:554)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:316)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onComplete(FlowableBuffer.java:152)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:215)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:394)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by OhMyLove666** [comment]
Some age-gated videos still tend to show error.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=61i0AoRh5Ws
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.21.6
* __OS:__ Linux Redmi/begonia/begonia:10/QP1A.190711.020/V12.0.7.0.QGGMIXM:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.AgeRestrictedContentException: This age-restricted video cannot be watched.
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:752)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by opusforlife2** [comment]
> Some age-gated videos still tend to show error.

Indeed. The PR seems to have fixed some videos, but not all.

**Comment by TobiGr** [comment]
[NewPipe_v0.21.6_RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/6760399/NewPipe_v0.21.6_RC2.zip).
The second and probably last release candidate for 0.21.6 comes with fixes for the YouTube consent cookie, a fixed crash that occurred when connecting the device to a car's Bluetooth and updated translations.

@SameenAhnaf I was not able to reproduce your crashes. Did you import old feeds and bookmarks or did you create new ones?

**Comment by TobiGr** [comment]
[NewPipe_v0.21.6_RC3.zip](https://github.com/TeamNewPipe/NewPipe/files/6760427/NewPipe_v0.21.6_RC3.zip) fixes empty strings when using a Chinese localization.

**Comment by SameenAhnaf** [comment]
@TobiGr Clear app data, import your database and you will begin to notice them only for a first few hours. If you don't import database, the bugs don't seem to appear.

I found out some more bugs. These bugs tend to behave the same way.

3. Subscribing or unsubscribing to a channel seems to be impossible.


<details><summary>Bug Report</summary>

## Exception
* __User Action:__ subscription change
* __Request:__ Changing subscription for https://www.youtube.com/channel/UC2WuPTt0k8yDJpfenggOAVQ
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.21.6
* __OS:__ Linux Redmi/begonia/begonia:10/QP1A.190711.020/V12.0.7.0.QGGMIXM:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
	at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:502)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:74)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:486)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at org.schabi.newpipe.database.subscription.SubscriptionDAO_Impl.delete(SubscriptionDAO_Impl.java:240)
	at org.schabi.newpipe.database.subscription.SubscriptionDAO_Impl.delete(SubscriptionDAO_Impl.java:27)
	at org.schabi.newpipe.local.subscription.SubscriptionManager.deleteSubscription(SubscriptionManager.kt:95)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.lambda$mapOnUnsubscribe$3$ChannelFragment(ChannelFragment.java:259)
	at org.schabi.newpipe.fragments.list.channel.-$$Lambda$ChannelFragment$eO2Vi4d3E1jdZvQonqJR0OVT01o.apply(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
	at io.reactivex.rxjava3.observers.SerializedObserver.onNext(SerializedObserver.java:113)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

</details>

4. No way to add or remove a playlist.


<details><summary>Bug Report</summary>

## Exception
* __User Action:__ bookmark
* __Request:__ Adding playlist bookmark
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Redmi/begonia/begonia:10/QP1A.190711.020/V12.0.7.0.QGGMIXM:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
	at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:502)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:74)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:486)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at org.schabi.newpipe.database.playlist.dao.PlaylistRemoteDAO_Impl.upsert(PlaylistRemoteDAO_Impl.java:238)
	at org.schabi.newpipe.local.playlist.RemotePlaylistManager.lambda$onBookmark$1$RemotePlaylistManager(RemotePlaylistManager.java:39)
	at org.schabi.newpipe.local.playlist.-$$Lambda$RemotePlaylistManager$TexHkGtzshvlLIp_-4QeooeoZoo.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

</details>

**Comment by el-banto** [comment]
After installing the app and importing my settings and subscriptions, refreshing my feed causes this exception.

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.database.subscription.SubscriptionEntity.setData(java.lang.String, java.lang.String, java.lang.String, java.lang.Long)' on a null object reference
	at org.schabi.newpipe.local.subscription.SubscriptionManager.updateFromInfo(SubscriptionManager.kt:75)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1$1.run(FeedLoadService.kt:324)
	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:556)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:316)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onNext(FlowableBuffer.java:124)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by el-banto** [comment]
Also when I don't import my settings and subscriptions, but rather add them manually, after refreshing the feed it says "Feed last updated: 4 minutes ago" rather than "Feed last updated: moments ago".

**Comment by SameenAhnaf** [comment]
> Also when I don't import my settings and subscriptions, but rather add them manually, after refreshing the feed it says "Feed last updated: 4 minutes ago" rather than "Feed last updated: moments ago".

That's probably because the default setting of "Feed Update threshold" is "5 minutes".

![IMG_20210706_020748](https://user-images.githubusercontent.com/79245641/124514593-36c1c680-ddff-11eb-96db-4683927ad45c.jpg)

**Comment by opusforlife2** [comment]
@TobiGr How strange. RC3 doesn't install over RC1. Did the signing keys change?

**Comment by TobiGr** [comment]
i took the builds from the CI. that's indeed strange. I'll look into it later.

**Comment by TobiGr** [comment]
I think we should try to revert #5462 to fix the transaction problems (https://github.com/TeamNewPipe/NewPipe/issues/6577#issuecomment-869025137, https://github.com/TeamNewPipe/NewPipe/issues/6577#issuecomment-873668659). From the [`@Transation` docs](https://developer.android.com/reference/androidx/room/Transaction):
> Marks a method in a Dao class as a transaction method.
>
>When used on a non-abstract method of an **abstract Dao class**, the derived implementation of the method will execute the super method in a database transaction. All the parameters and return types are preserved. The transaction will be marked as successful unless an exception is thrown in the method body. 

@TacoTheDank  @Isira-Seneviratne What do you think?

**Comment by TobiGr** [comment]
@SameenAhnaf Please test this APK and let me know if we fixed the database transaction crashes: [transaction.zip](https://github.com/TeamNewPipe/NewPipe/files/6777771/transaction.zip)

**Comment by SameenAhnaf** [comment]
@TobiGr Unfortunately, no. I tried to do following things.
1. I subscribed to a few channels and playlists randomly.
2. Then I exported database.
3. The app data was cleared.
4. I imported database from the recently made file in step-2.
5. Same database errors are still shown.

I followed these steps to make sure that there's nothing wrong with my personal database. Also, the bugs seem to persist no matter if you import settings or not.

**Comment by TobiGr** [comment]
I still cannot reproduce the bug, can you try this apk as well? [room.zip](https://github.com/TeamNewPipe/NewPipe/files/6778695/room.zip)

**Comment by TacoTheDank** [comment]
@TobiGr I'd say that if trying to fix the issue starts to feel like more of a hassle than it's worth, then it would probably be better to just revert the change until we can find a better solution (at least so that it doesn't end up stalling the release process).

**Comment by Thewisem** [comment]
Yeah this issue still persists.
Steps
1) Open Newpipe
2) Click on a video
3) Escape from newpipe
4) Go to notification panel and click on repeat

It is happening n android 7 tablet. And is happening on this version as well

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.debug.release0216.player.MainPlayer.REPEAT flg=0x10000010 launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } bqHint=0 bnds=[376,187][424,235] } in org.schabi.newpipe.player.Player$3@f74bbd3
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.ClassCastException: android.widget.ImageButton cannot be cast to androidx.appcompat.widget.AppCompatImageButton
	at org.schabi.newpipe.player.Player.onRepeatModeChanged(Player.java:2263)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$setRepeatMode$2(ExoPlayerImpl.java:564)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$rgrcbaqP9Y8LgzdByBnAfUO4ydU.invokeListener(lambda)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6(ExoPlayerImpl.java:1318)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$b59raXxaB-trjwE5bgpZInm1QnU.run(lambda)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1318)
	at com.google.android.exoplayer2.ExoPlayerImpl.setRepeatMode(ExoPlayerImpl.java:564)
	at com.google.android.exoplayer2.SimpleExoPlayer.setRepeatMode(SimpleExoPlayer.java:1636)
	at org.schabi.newpipe.player.Player.setRepeatMode(Player.java:2253)
	at org.schabi.newpipe.player.Player.onRepeatClicked(Player.java:2232)
	at org.schabi.newpipe.player.Player.onBroadcastReceived(Player.java:1123)
	at org.schabi.newpipe.player.Player.access$200(Player.java:190)
	at org.schabi.newpipe.player.Player$3.onReceive(Player.java:1060)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
	... 7 more

```
</details>
<hr>

**Comment by TobiGr** [comment]
@Thewisem That's a different issue. I tried to fix it in #6622. Could you please test the APK from that PR?

**Comment by Thewisem** [comment]
If your taking about this apk, then it doesn't work on this one

**Comment by Stypox** [comment]
I also get crashes after importing the database and refreshing feed:

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.database.subscription.SubscriptionEntity.setName(java.lang.String)' on a null object reference
	at org.schabi.newpipe.local.subscription.SubscriptionManager.updateFromInfo(SubscriptionManager.kt:73)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1$1.run(FeedLoadService.kt:324)
	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:556)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:316)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onNext(FlowableBuffer.java:124)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>
And the second time I reloaded feed I got this:

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
	at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:502)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:74)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:486)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:554)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:316)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onComplete(FlowableBuffer.java:152)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:215)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:394)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>


Also for some reason all of my local playlists seem to be missing

I also get errors on unsubscribing:

## Exception
* __User Action:__ subscription change
* __Request:__ Changing subscription for https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
	at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:502)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:74)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:486)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at org.schabi.newpipe.database.subscription.SubscriptionDAO_Impl.delete(SubscriptionDAO_Impl.java:240)
	at org.schabi.newpipe.database.subscription.SubscriptionDAO_Impl.delete(SubscriptionDAO_Impl.java:27)
	at org.schabi.newpipe.local.subscription.SubscriptionManager.deleteSubscription(SubscriptionManager.kt:95)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.lambda$mapOnUnsubscribe$3$ChannelFragment(ChannelFragment.java:259)
	at org.schabi.newpipe.fragments.list.channel.-$$Lambda$ChannelFragment$eO2Vi4d3E1jdZvQonqJR0OVT01o.apply(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
	at io.reactivex.rxjava3.observers.SerializedObserver.onNext(SerializedObserver.java:113)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

I will have time for investigating myself tomorrow afternoon

**Comment by opusforlife2** [comment]
I haven't encountered any crashes after importing my database. But I always close and reopen Newpipe after the import finishes. Are you guys doing the other actions without restarting Newpipe at least once when you encounter these crashes?

**Comment by mhmdanas** [comment]
@opusforlife2 I get all the errors below without restarting the app after import, but after restarting everything works smoothly.

I always get this error on feed refresh (regardless of if it's the first time or not, and it happens close to the end of the refresh):
## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.database.subscription.SubscriptionEntity.setData(java.lang.String, java.lang.String, java.lang.String, java.lang.Long)' on a null object reference
	at org.schabi.newpipe.local.subscription.SubscriptionManager.updateFromInfo(SubscriptionManager.kt:75)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1$1.run(FeedLoadService.kt:324)
	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:556)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:316)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onNext(FlowableBuffer.java:124)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>
I get this error on opening ANY channel for the first time (that is, if I open channel A, I get this error, but if I open channel B afterwards or even re-open channel A, I get another error that I will show next):

## Exception
* __User Action:__ subscription update
* __Request:__ Updating subscription for https://soundcloud.com/hinkik
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ SoundCloud
* __Version:__ 0.21.6
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:957)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:792)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:90)
	at androidx.room.RoomDatabase.internalEndTransaction(RoomDatabase.java:510)
	at androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:500)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl.setLastUpdatedForSubscription(FeedDAO_Impl.java:206)
	at org.schabi.newpipe.local.feed.FeedDatabaseManager.upsertAll(FeedDatabaseManager.kt:101)
	at org.schabi.newpipe.local.feed.FeedDatabaseManager.upsertAll$default(FeedDatabaseManager.kt:78)
	at org.schabi.newpipe.local.subscription.SubscriptionManager$updateChannelInfo$1$1.run(SubscriptionManager.kt:65)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:35)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatMapCompletable$FlatMapCompletableObserver.onSuccess(MaybeFlatMapCompletable.java:91)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:62)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatMapCompletable.subscribeActual(MaybeFlatMapCompletable.java:44)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>
I get this error when I open a channel (not for the first time, see above):

## Exception
* __User Action:__ subscription update
* __Request:__ Updating subscription for https://soundcloud.com/hinkik
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ SoundCloud
* __Version:__ 0.21.6
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR[1])
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:957)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:772)
	at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:706)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:74)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:486)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at org.schabi.newpipe.database.subscription.SubscriptionDAO_Impl.update(SubscriptionDAO_Impl.java:267)
	at org.schabi.newpipe.database.subscription.SubscriptionDAO_Impl.update(SubscriptionDAO_Impl.java:27)
	at org.schabi.newpipe.local.subscription.SubscriptionManager$updateChannelInfo$1$1.run(SubscriptionManager.kt:64)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:35)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatMapCompletable$FlatMapCompletableObserver.onSuccess(MaybeFlatMapCompletable.java:91)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:62)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatMapCompletable.subscribeActual(MaybeFlatMapCompletable.java:44)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

The playlists tab gives this error (it worked fine the first time, but when I reset the app's storage and imported my data again it doesn't for some reason):

## Exception
* __User Action:__ bookmark
* __Request:__ Loading playlists
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR[1])
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:957)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:772)
	at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:706)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:74)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:486)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:438)
	at org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:435)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:131)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)
	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

**Comment by SameenAhnaf** [comment]
Hopefully, restarting the app solves the bugs for me. But the app never misbehaved in the past.

I am not sure if it is a standard practice to restart the app after applying every single setting. However, if such a bug is inevitable at this moment, 'Requires app restart to have app effect' subnote should be added.

**Comment by mhmdanas** [comment]
Since yours truly had some time on his hands, he decided to bisect the issue, and he found out that the first bad commit is 90de75968df659b9e2e2c58df5f847e549265180 from #6495.

**Comment by TobiGr** [comment]
I compiled a test version without the changes from #6495. Please test if the database error is gone.
[0.21.6_no_6495.zip](https://github.com/TeamNewPipe/NewPipe/files/6794880/0.21.6_no_6495.zip)

**Comment by TobiGr** [comment]
Another test APK which (hopefully) fixed the bug introduced in #6495 without reverting the PR: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6794906/app-debug.zip)

**Comment by el-banto** [comment]
> Another test APK which (hopefully) fixed the bug introduced in #6495 without reverting the PR: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6794906/app-debug.zip)
> 

Thank you, I'm no longer getting any errors when refreshing my imported subscriptions.

I did still having that issue I mentioned earlier when after refreshing it still doesn't say "Feed last updated: moments ago", in fact it says last updated 5 days ago which is when the database export was created. However simply restarting the app fixed it.

**Comment by TobiGr** [comment]
>  I'm no longer getting any errors when refreshing my imported subscriptions.

Perfect! I opened #6639.

> I did still having that issue I mentioned earlier when after refreshing it still doesn't say "Feed last updated: moments ago", in fact it says last updated 5 days ago which is when the database export was created. However simply restarting the app fixed it.

@el-banto Can you open a new issue describing the problem so we do not forget about it. I do not want to fix this issue in this release, because this is only a minor issue and the release process was already halted for too long.

**Comment by skyGtm** [comment]
"What's new" Section **BUG**

#### Steps to Reproduce:
1. Go to what's new section.
2. Pull down to refresh.
3. (If new videos are available) You have to manually scroll up to see the latest videos.

**Comment by TobiGr** [comment]
@skyGtm I cannot reproduce that. Please give us some more info on your device and Android version

**Comment by skyGtm** [comment]
Device: Huawei Nova 3i
OS : Android 9

**Comment by Thewisem** [comment]
Has anyone had problems with lag?

**Comment by Thewisem** [comment]
Cause it WAS a problem. Maybe we could ask the people on THAT issue whether it still persists

**Comment by el-banto** [comment]
> @el-banto Can you open a new issue describing the problem so we do not forget about it. I do not want to fix this issue in this release, because this is only a minor issue and the release process was already halted for too long.

Will do!

> "What's new" Section **BUG**
> 
> #### Steps to Reproduce:
> 1. Go to what's new section.
> 2. Pull down to refresh.
> 3. (If new videos are available) You have to manually scroll up to see the latest videos.

I have noticed this as well

OS: Android 10
Device: OnePlus 6

**Comment by Thewisem** [comment]
Any ideas on the playlist issue?
https://github.com/TeamNewPipe/NewPipe/issues/5203

**Comment by skyGtm** [comment]
>Please give us some more info on your device and Android version

(If new videos are available) You have to manually scroll up to see the latest videos.

https://user-images.githubusercontent.com/50160188/125167877-60de0480-e1c2-11eb-88e4-115c6c0b2598.mp4

@TobiGr here is the video

**Comment by Thewisem** [comment]
Why did the video pattern change? Strange

**Comment by el-banto** [comment]
The videos changing order seems to happen for videos which were released very close to each other (same hour or so). Perhaps the sorting is based on the hour?

**Comment by TobiGr** [comment]
@skyGtm Thank you for the screencast. I am able to reproduce this now. I tried to fix this, but was just partly successful. This is only a minor regression. For this reason we'll proceed with releasing 0.21.6. Please open a new issue with the details from you two comments. I aim to fix this in the next version.
