### ISSUE TITLE
Consider to release v0.10.0

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#682]
Can we now consider to release version v0.10.0?
Now where more or less all feature work stable enough to be usable.

**Comment by wb9688** [comment]
@theScrabi: Can we at least update NewPipeExtractor first now that it
supports decrypting URLs correctly again?

And how about multiple services? Or will we do that with the release after
v0.10.0?

**Comment by theScrabi** [comment]
I'm not a huge fan, of putting to much changes into one version. Because the more U change the more unstable it gets. Also I made the experience that user will find bugs you aren't aware of.

I'd like to release now, and than if someone finds a bug we can re release again.

We can consider multi service support in a few versions but not now.

**Comment by wb9688** [comment]
@theScrabi: I'm OK with releasing now, but only if we update
NewPipeExtractor first.

I'm not a fan of too much changes in one release either.

We already have it in NewPipeExtractor, btw I'm working on adding it to
NewPipe, but I've been really busy the last few days.

**Comment by theScrabi** [comment]
@mauriciocolli updated the extractor [here](https://github.com/TeamNewPipe/NewPipe/commit/23f70d6b8b04bb7ba6483b54d042f6f094f71775)

**Comment by mauriciocolli** [comment]
I already updated the extractor https://github.com/TeamNewPipe/NewPipe/commit/23f70d6b8b04bb7ba6483b54d042f6f094f71775.

But one thing to always keep in mind when updating is the database. If we update carelessly we could end up clearing the database, which is not very cool.

**PS:** It still have some nasty bugs in the extractor, so I wouldn't recommend release right now (YouTube has been changing in the past days).

**Comment by wb9688** [comment]
Oh, I didn't notice. But if there are some nasty bugs, I'd wait indeed.

**Comment by theScrabi** [comment]
This is why we should consider to have a beta app. Because there will always be bugs. Some people can get along with a few bugs some can't. If we have beta people could decide them selfs.

**Comment by wb9688** [comment]
@theScrabi: I agree, but what'll we do with version numbering?

**Comment by theScrabi** [comment]
I'd do it the way we do it now, just put a beta in front of the version. like
v0.10.0
v-beta-0.10.1 or beta-v0.10.1

**Comment by theScrabi** [comment]
> YouTube has been changing in the past days

I saw that. Due to that new UI some of the things that still work are rather unclear if they will work in the future. 
Example: Inn the channels view on youtube there was a "load next" button. We used that button to get the url for the ajax request for the next video items. This button does not exist in the new UI anymore. It seems NP is till capable to load the old website where this button still exists. But for how long?

**Comment by mauriciocolli** [comment]
I fixed some error that caused these annoyances (at least the ones that I noticed), but just a brief summary:
- Uploader name when getting next streams
- Trying to extract YouTube mix from search was resulting in error

They are very annoying because **_every time_** they ask the user to report (in almost _every_ search, in every "next videos"...).

**Comment by theScrabi** [comment]
Yea. I see.

**Comment by theScrabi** [comment]
Although these are extractor related bugs right? I have to admid that It's not that bad. Over all NewPipe is pretty usable. So form my experience of usage I'd vote for release.

Anyway is the database still an issue tho?

**Comment by mauriciocolli** [comment]
Well, it **_was_** bad before I fixed them (asking the user to report to do the most trivial of things like search).

The database was more of a warning about the fact that we'd have to create multiple tiny migrations, which is not ideal.  But that will not be a problem anymore as we'll have a different build so we can see when it's the best moment to release.

**Comment by theScrabi** [comment]
Well if its not the code, then there is nothing that can prevent us from release.

**Comment by theScrabi** [comment]
So I've released:
https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.10.0

Shame on me if something went wrong.

**Comment by TobiGr** [comment]
> Open youtube links directly from search (fixes #35) #692
> Support dark theme in file picker #699 (fixes #646)

Correct me if I am wrong but I think these two were only merged to `dev` branch.

**Comment by theScrabi** [comment]
you are right :) removed it

**Comment by rbozan** [comment]
The version of NewPipe on fdroid hasn't updated I think

**Comment by theScrabi** [comment]
Several apps on fdroid haven't updated yet. I don't know what takes them so long again.
