### ISSUE TITLE
Fullscreen sometimes show a quarter of a screen [Android 12]

### ISSUE THREAD

**Issue by privacyonly** [TeamNewPipe/NewPipe#7262]
ℹ️ **Please don't leave a comment like "I am having the same issue" without additional information. Simply upvote the issue instead.**

### Checklist

- [x] I am using the latest version - 0.21.12 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. open new pipe
2. press on any videos
3. press play
4. press on the full screen

### Actual behavior

it is a quarter of full screen on the top left corner of the screen

### Expected behavior

full screen

### Screenshots/Screen recordings

https://player.vimeo.com/video/633798373

### Device info

 - Android version/Custom ROM version: Android 12 OneUI 4.0 beta 2 official ZUJ1
 - Device model: SM-G998B Samsung Galaxy S21 Ultra 5G

**Comment by litetex** [comment]
Maybe #7005 (this PR updates ExoPlayer) solves this problem.

**Comment by Coderdude112** [comment]
Also having this problem. Pixel 3. seems to happen randomly

**Comment by opusforlife2** [comment]
@Coderdude112 Did you try the APK suggested in the comment above yours?

**Comment by Coderdude112** [comment]
Not yet, ill give it a try today

**Comment by Nfnfjfjjf** [comment]
> Maybe #7005 (this PR updates ExoPlayer) solves this problem.

Tested apk seems to have solved the issue

**Comment by privacyonly** [comment]
it is not fixed with the latest 0.21.14

**Comment by Sagittarisus** [comment]
Experiencing the same issue, something caused it to break inside of the latest build, it was fixed when exoplayer was updated before.

**Comment by xelaseer** [comment]
Can confirm this issue also exists on my phone on 0.21.15.

Google Pixel 4XL, with the latest Graphene OS.

Appears to happen consistently, but randomly, with full screen achievable with several attempts to rotate.

**Comment by VinnyVynce** [comment]
I have the same issue on my Pixel 6 with the latest version of GrapheneOS (Android 12). I'm using the latest release of NewPipe.

**Comment by Sagittarisus** [comment]
I was able to compile the newpipe app from source code, and one of the commits which were done after the official newest release has fixed the issue as I do not experience it any more.

**Comment by litetex** [comment]
> I was able to compile the newpipe app from source code

You can also use the latest CI build of the ``dev`` branch:
Currently:
* Build: https://github.com/TeamNewPipe/NewPipe/actions/runs/1669365449
* Direct download: https://github.com/TeamNewPipe/NewPipe/suites/4867108835/artifacts/138726644

However we didn't fix something player-specific - at least of what I'm aware of.
Maybe #7499 fixed it? ``¯\_(ツ)_/¯``

**Comment by Khyta** [comment]
I have the same issue.

GrapheneOS stable on Pixel 6
NewPipe version 0.21.15

**Comment by litetex** [comment]
Pleas stop commenting "I have the same problem" on Android 12. Simply give the issue an upvote 😄

**Comment by VinnyVynce** [comment]
I've tried the artifact linked by @litetex but for me the issue still happens.

**Comment by privacyonly** [comment]
one thing I am very sure of, this issue doesn't affect any android tablet, windows 11 wsa, or any android phone with tablet mode on(change settings > appearance > tablet mode to on).

**Comment by pizzapim** [comment]
It seems the bug doesn't happen when I have the video paused and I press the fullscreen button. Only when the video is playing and then I press the fullscreen button, it sometimes takes only a quarter of the screen.

Google Pixel 4a, GrapheneOS 12

**Comment by chpio** [comment]
> It seems the bug doesn't happen when I have the video paused and I press the fullscreen button. Only when the video is playing and then I press the fullscreen button, it sometimes takes only a quarter of the screen.

yeah, that was my first workaround. The second (works much better) is to set the default to be fullscreen. Changing the fit/fill/zoom option also fixes it.

The fullscreen by default option makes vertical videos show up horizontally.

**Comment by swarupbhanjachowdhury** [comment]
Same happening with me.

**Comment by j-james** [comment]
> try settings > video and audio > turn on start main player in fullscreen.

This doesn't appear to fix it.

I've frequently run into this bug for the last couple of versions on a Pixel 4a with GrapheneOS. Here is a  screenshot of the bug:
![Screenshot_20220214-010522](https://user-images.githubusercontent.com/35242550/153834003-3c665fd4-3a15-4af5-9e81-7de213e63f44.png)

I can inconsistently get the bug to trigger when turning my phone from vertical orientation to horizontal orientation while playing a video. This seems random - it doesn't seem to matter if I just unpaused it or had switched orientations before when triggering this bug.

I can never get it to trigger when unpausing a video in landscape mode. Something to do with the change in orientation is triggering the bug.

I can also never get it to trigger when switching orientations with a paused video, because it goes into the top-half-video bottom-half-description mode.

I wonder if it has something to do with the "tall" aspect ratio of the S21 and Pixel phones?

**Comment by marmotton** [comment]
Hello,
this also happens with this setup:
* NewPipe 0.22.0
* Google Pixel 4a
* CalyxOS 3.2.0
* Android 12

**Comment by blaueente** [comment]
Additional information: I tried a screen recording as well, but there is an additional artifact that does *not* show on the screen recording: a vertical "glitch" bar, about 0.5 cm wide, about 1/4 from the left edge of the phone.
It is very bright, kind of *static*, appears and disappears, changes its width slightly, and wanders around a bit.
When I restore the proper fullscreen view (e.g. by selecting another aspect ratio/zoom, and then switching back), the glitch is not present anymore.

**Device:** Google Pixel 6 Pro
**Android version:** 12 (SQ1D.220205.004)
**Newpipe version:** 0.22.0

**Comment by navilg** [comment]
Same issue with my phone as well. When switching to full screen, it start playing video in first quarter of screen. Its inyermittent and with multiple attempt it works fine. Screenshot added.

Device: Samsung S21 plus
Android: 12
New Pipe version: 0.22.0 (It was present in previous versions as well)

**Comment by blake-haas** [comment]
Same issue on a Samsung note 20 ultra on Android 12. Happens almost every time I rotate the screen after starting a video. Might be in my mind but if I rotate very slowly sometimes it works. Probably just my mind though.

**Comment by VinnyVynce** [comment]
Since the latest build of GrapheneOS (march 11th 2022) I cannot reproduce this bug anymore and I had it every single day before on my Pixel 6. Being a sample size of one person I'm unsure if the latest release truly fixed it but would love to know from the other Graphene users.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Havent seen this in a while after latest update on GrapheneOS

**Comment by electricar** [comment]
I got the same issue on my S22+, Newpipe 0.22.1.
Android 12, One UI 4.1

**Comment by guido4000** [comment]
I have the same issue with a Flip 3, One UI 4.1, NewPipe 0.22.1

**Comment by TiA4f8R** [comment]
@electricar @guido4000 Can't you read this before posting a spam comment?

> Please stop commenting "I have the same problem" on Android 12. Simply give the issue an upvote 😄

**Comment by TiA4f8R** [comment]
Does the latest ExoPlayer update, 2.17.1, which changed several things for Android 12, fixes this issue? Please test the APK of #8020 (or any APK with this PR merged, if you want).

**Comment by d4f5409d** [comment]
Same here, OxygenOS 12, OnePlus 8

**Comment by TiA4f8R** [comment]
@d4f5409d From the debug APK or for the release APK? If that's the release one, please refrain this type of comment.

**Comment by silvaDominic** [comment]
Just upgraded to Android 12/OneUI 4 on a Samsung 10e and started getting this issue. Given that there are non-Samsung users citing the issue, this definitely seems linked to Android 12.

Present on NewPipe v22.1 and 22.2

**Comment by j-james** [comment]
Sounds like it. I'm also no longer experiencing this bug, either a GrapheneOS update or a NewPipe update fixed it for me.

**Comment by AlertSubject** [comment]
I updated to the latest version last night and I still experience the bug
Although less often as it seems

**Comment by hammolo** [comment]
The problem is still unresolved with the latest version.
Phone: Motorola Edge 30 Pro (with Android 12)
had the same issue with a Samsung Galaxy 21+ (with Android 12).
About 2 times out of 3, when i rotate the video, it only takes left upper quarter of the screen. By just rotating the phone back and forth a few times, it opens full screen.

**Comment by OhAsya** [comment]
I've been having this issue ever since getting my new phone. Samsung S22 Ultra, Android 12. New Pipe 0.23.0.

![Screenshot_20220620-070922_NewPipe SponsorBlock](https://user-images.githubusercontent.com/93078532/174529961-cde812f0-a04c-4b56-824d-dacb51db529e.png)

**Comment by navilg** [comment]
Is anyone working on this ?

**Comment by AlertSubject** [comment]
> Is anyone working on this ? 

https://github.com/TeamNewPipe/NewPipe/commit/dc7fce86a566b9360af4b855c06f4c08a3fce8be

Doesn't seem likely to be fixed in the next release based on the changelog so far

**Comment by privacyonly** [comment]
Funny enough that this cannot be reproduce in android emulator in android studio.

anyway
note to myself:
adding setRecovery();
at the end of public void onVideoSizeChanged(@NonNull final VideoSize videoSize) {
line3938 player.java

decrease the chance of getting quarter screen by a lot.

**Comment by AlertSubject** [comment]
Would it be worth to create a pull request as a "bandaid fix" for this?
This issue has been going on for over half a year now and I'd be happy with any change, even if it just reduces the chance

**Comment by privacyonly** [comment]
wait don't do the band aid. I found the real issue.
https://developer.android.com/about/versions/12/deprecations
so I found a lot of display.getsize in newpipe

**Comment by AlertSubject** [comment]
Is someone able to create a PR for this? I don't have any development experience sadly

**Comment by privacyonly** [comment]
I was about to edit the one above when I discover the final fix, like 100% fix.

I am new to coding so bear with me, I will try my best to create a PR.

I have no idea how this code work or break something

fragmentListener.onFullscreenStateChanged(isFullscreen);

I commented this and it works.

**Comment by blake-haas** [comment]
> 

without understanding why it is breaking and not having an idea of any regressions you may cause, that PR will surely not get approved.  Someone more experienced with newPipe needs to take a look at this issue.

**Comment by AlertSubject** [comment]
Is there someone that can be pinged for this or would that not be considered friendly?
I'm not too familiar with github etiquette

**Comment by opusforlife2** [comment]
Wow, don't discourage someone who's trying to do something productive, guys. Let @privacyonly experiment and learn. Even if the code isn't used, there will be real benefits.

**Comment by privacyonly** [comment]
ok. I found out what it broke, it is the android nav bar.

**Comment by d4f5409d** [comment]
> Funny enough that this cannot be reproduce in android emulator in android studio.
> 
> anyway
> note to myself:
> adding setRecovery();
> at the end of public void onVideoSizeChanged(@NonNull final VideoSize videoSize) {
> line3938 player.java
> 
> decrease the chance of getting quarter screen by a lot.

I guess because it's an Android bug, not an app bug.

**Comment by privacyonly** [comment]
can someone please try the apk above and give a feedback?

**Comment by AlertSubject** [comment]
> can someone please try the apk above and give a feedback?

![Screenshot_2022-06-28-13-52-09-64_3d73e98b1ad3bd2575f7a56513d89a0c.jpg](https://user-images.githubusercontent.com/72819077/176171839-39a14da2-06ae-4659-a00f-659699a9b886.jpg)

**Comment by AndyP435** [comment]
This bug affects my phone Galaxy S20 FE 5G, Android 12. Screen resolution 1080x2400, newest version on FDroid as of June 29. I also tried the apk from PrivacyOnly edit 4 and got the "package appears to be invalid" message.

**Comment by StefMarko** [comment]
I am having the same issue.
Android 12, galaxy a52s with one ui 4.1.

**Comment by barackenkumpel** [comment]
> did it fix this problem?

Yes, very well. 
But the Overlay behaves kinda flashy now

https://user-images.githubusercontent.com/93818968/177987485-08f8a77e-eeaf-4f95-971d-940935a3f5e7.mp4

**Comment by Donkey-Doug** [comment]
> I didn't observe the problem so far so I assume it's somewhat device or software specific.

I have had this issue for a very long time. I believe it happens when a video is still loading (video fully black) and I press maximize. In my case, however, it is always half the screen and not a quarter. 

Android 10
Xiaomi mi 9t pro
Lineageos without google

**Comment by AlertSubject** [comment]
Half the screen happens when you have your video size set to "fill" I think
At least either of the two other screen size options produces another outcome than when you use the default video size option. This one produces the "quarter of the screen video"

**Comment by Stypox** [comment]
Could you try if, by any chance, #8170 fixes the issue? It probably does not, but let's check. This is the direct url to the APK built by the CI: https://github.com/TeamNewPipe/NewPipe/suites/7295032495/artifacts/294324129

Btw @privacyonly, there is no need to upload APKs to Mega, you can just zip them and then upload them here.

**Comment by yamatt** [comment]
@Stypox I've just tried it out and it looks like it's resolved the issue.

I went into full screen many times and it would always open on the whole screen whereas the current release is maybe 50% of the time.

**Comment by privacyonly** [comment]
@Stypox, yes this fix the issue, thanks.

**Comment by AlertSubject** [comment]
> Could you try if, by any chance, #8170 fixes the issue? It probably does not, but let's check. This is the direct url to the APK built by the CI: https://github.com/TeamNewPipe/NewPipe/suites/7295032495/artifacts/294324129


I'm getting a 404 file not found error

**Comment by privacyonly** [comment]
@AlertSubject login, refresh, download again, it is a zip file.

**Comment by AlertSubject** [comment]
> @AlertSubject login, refresh, download again, it is a zip file.

Link works fine on Desktop
Github mobile app not so much
thanks, will test the app

**Comment by wanderinglethe** [comment]
#8170 this is only merged into dev, so isn't merged into master yet and therefore not in 0.23.2, right?

(Having the same problems on S21FE, OneUI 4.1 with NewPipe version 0.23.2, except that the "sometimes" is more of an almost always)

**Comment by Stypox** [comment]
> isn't merged into master yet and therefore not in 0.23.2, right?

Yes

**Comment by navilg** [comment]
Are we still getting this issue ? I don't see it anymore in my phone.

**Comment by AlertSubject** [comment]
> Are we still getting this issue ? I don't see it anymore in my phone. 

Resolved for me

**Comment by opusforlife2** [comment]
Hence, why the issue is closed.
