### ISSUE TITLE
Constantly getting "Newpipe isn't responding" popups randomly while watching Youtube videos

### ISSUE THREAD

**Issue by 32423d** [TeamNewPipe/NewPipe#9390]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.1

### Steps to reproduce the bug

This issue randomly occurs for me.
Steps to reproduce:
1. Open and play a Youtube video or a few Youtube videos
2. Watch videos until the popup occurs
3. Popup occurs again a few seconds after closing it with the wait button and keeps occurring every time it is closed by the wait button

### Expected behavior

The expected behavior is for the popup to show up when the app is actually unresponsive. The app is fully responsive right before the popup shows up and whenever I close the popup the app is still fully responsive after. 

### Actual behavior

The "Newpipe isn't responding" keeps appearing randomly whenever I am watching Youtube videos with Newpipe. I haven't found anyway to reliable reproduce the issue but it occurs randomly for me whenever I am just watching Youtube videos. 

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/95009201/201498405-eb6559ee-23b6-47dd-9b6b-ede5bbbb8943.png)

### Affected Android/Custom ROM version

Android 13 stable

### Affected device model

Google Pixel 5a

### Additional information
I found this bug occurring in the official Newpipe app that is run by the Newpipe team.

**Comment by 32423d** [comment]
> Try clearing cache check it if it works If not take a backup of database by settings> content> export database Then reimport using settings> content> import database

I cleared the cache and re-imported my database file but it still didn't fix the issue.
![image](https://user-images.githubusercontent.com/95009201/201512091-5ef967fe-3c4d-49a4-8dd5-38270e4a882e.png)

**Comment by 32423d** [comment]
> Try clearing cache check it if it works If not take a backup of database by settings> content> export database Then reimport using settings> content> import database

I cleared the app cache and re-imported my Newpipe database file but the issue is still occurring for me. 
![image](https://user-images.githubusercontent.com/95009201/201512213-63aa38d3-0b4f-4778-a983-bf0d8d206dfb.png)

**Comment by 32423d** [comment]
I tried again by clearing the app cache and not re-importing the Newpipe database file but the issue still occurred after watching some videos right after.

**Comment by xearonet** [comment]
Same for me. I also tried remove app completely and install again. Same result.

Spec: 
Xiaomi mi 9se
Android 10
Miui 11

**Comment by blaueente** [comment]
Same here
Google Pixel 6 Pro
Android 13

**Comment by russdill** [comment]
Yes, I even got the same thing on a completely fresh install without any imported settings when trying out the pre 0.24.1 release.

Pixel 6 Pro
Android 13

**Comment by 32423d** [comment]
I have uninstalled and reinstalled multiple times already and this issue persists.

**Comment by 32423d** [comment]
One thing I have noticed is that when I downgraded to v0.23.3 the issue does not occur but when using v0.24.0 and v0.24.1 the issue occurs so I believe that whatever is causing the issue is something that was changed in version v0.24.0.

**Comment by IndigoJay** [comment]
I am experiencing this bug too

Pixel 6 Pro
Android 13

**Comment by AudricV** [comment]
As this issue is hard to reproduce, we can't reproduce it on our side and trace the origin of the ANR (Application Not Responding), even if we know that the issue comes from the player.

Collecting logs from ADB's logcat when this issue occur would be a great first step to debug this issue (remember to remove personal information in logcats before posting them publicly).

**Comment by opusforlife2** [comment]
> remember to remove personal information in logcats before posting them publicly

If you have root, using App Manager's in-built Log Viewer lets you toggle a setting to do some of this automatically. It won't remove everything, but it will make it easier for you to do the rest.

**Comment by FrostKiwi** [comment]
Waited a bit before reporting it myself, but has been going on for over a month now, on roughly every 3rd Video I watch.
Google Pixel 6 Pro, Android 13

https://user-images.githubusercontent.com/60887273/209430756-8439cb8a-1b1f-48c4-8d64-7ef0eeb2fff5.mp4

Happens completely randomly. And the weird thing is, the App functions 100% fine. It's just the message...

**Comment by b1k3rdude** [comment]
I am getting the same issue, logged a tracker #9652 - https://github.com/TeamNewPipe/NewPipe/issues/9652

**Comment by FrostKiwi** [comment]
> Just commented [here](https://github.com/TeamNewPipe/NewPipe/issues/9030#issuecomment-1374980731) but I may have found a way to reproduce this. Watch a video, minimize the player to where you can browse other videos and then click on another video without closing the first video. It will take a few minutes for the ANR dialogue to popup.
> 
> I have found that if you close the video player before clicking on another video, the ANR dialogue won't popup.

Just wanted to clarify, that with my Pixel 6 Pro, it happens also randomly, without interaction. Like 5 mins into watching a video...

**Comment by kj** [comment]
This is still happening for me in version 0.25.0 RC2 #9712. Makes the app nearly unusable as even if you choose 'Wait', the dialog just comes up again a few seconds later.

**Comment by Stypox** [comment]
I think this is related to "ForegroundServiceDidNotStartInTime" or something, #9358

**Comment by FrostKiwi** [comment]
Updates to 0.25.0.
Still happening on my Pixel 6 Pro. Every 3rd or so video starts to display the `app not repsonding` dialog after 2 minutes or so of video run time, while the app itself runs fine. Have to then close the app -> reopen -> go to history -> continue video.

**Comment by Haprus** [comment]
The issue happens for me as well.

**Comment by 32423d** [comment]
I just used Newpipe again and this issue is occurring for me on the latest version of v0.25.0.

**Comment by Douile** [comment]
After this starts happening if you close the player: minimise the video and swipe down on it. You get the following crash (it seems to be related to streamdialogentry, my guess is enqueing). It could be entirely unrelated, but it only happens to me after the not responding prompts, so hopefully it is helpful in finding the root cause of the issue.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e2722f4 u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2005)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1976)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnPlayer(NavigationHelper.java:193)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnPlayer(NavigationHelper.java:203)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.lambda$static$2(StreamDialogDefaultEntry.java:54)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.$r8$lambda$HrNW3ftQD3NQNetYZjrz1JDwzD4(StreamDialogDefaultEntry.java:0)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry$$ExternalSyntheticLambda15.accept(R8$$SyntheticClass:0)
	at org.schabi.newpipe.util.SparseItemUtil.fetchItemInfoIfSparse(SparseItemUtil.java:54)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.lambda$static$3(StreamDialogDefaultEntry.java:53)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.$r8$lambda$vJPfXGxkVEGzC3RaucaklOZ4WRo(StreamDialogDefaultEntry.java:0)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry$$ExternalSyntheticLambda5.onClick(R8$$SyntheticClass:0)
	at org.schabi.newpipe.info_list.dialog.InfoItemDialog.lambda$new$2(InfoItemDialog.java:76)
	at org.schabi.newpipe.info_list.dialog.InfoItemDialog.$r8$lambda$rolB38hFbFwRPfIy0nmFKZx8iWo(InfoItemDialog.java:0)
	at org.schabi.newpipe.info_list.dialog.InfoItemDialog$$ExternalSyntheticLambda2.onClick(R8$$SyntheticClass:0)
	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3270)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4248)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3989)
	at android.view.View.dispatchTouchEvent(View.java:15010)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:911)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15269)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6654)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6454)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5910)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6098)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6155)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8989)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8940)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8909)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9112)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	... 5 more

```
</details>
<hr>

**Comment by av01d1ngx4** [comment]
The failure to launch a foreground service within the specified time frame is indicated by this error message in Android. In more detail "startForegroundService()"` was called, however `"Service"` failed to call `"startForeground()"` within a predetermined time frame, causing the system to throw an exception.

According to the error message, the class `"PlayerService" `and package `"org.schabi.newpipe" `are where the error occurred. It appears that after `"startForegroundService()"` was called, this `"Service"` did not call `"startForeground()"` promptly.

Because foreground services are used to execute long-running processes that are vital to the user, the system mandates that they be launched with a visual notification to the user. If a `"Service"` fails to initiate the notification within a specified time limit, the system suspects something has gone wrong and throws this exception.

To correct this mistake, ensure that the` "startForeground()"` function is invoked immediately after the `"startForegroundService()"` method. You may also need to optimize the code in order for the `"Service"` to start as rapidly as possible. Furthermore, you should verify that the notification utilized by the foreground service is meaningful and provides the user with important information.

**Comment by Douile** [comment]
Repeating this i got a different error 😔 using the same technique 


## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ca29cae u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2005)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1976)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openMainPlayer(VideoDetailFragment.java:1167)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$7cA0nfOW4EXxLpA03fs92UQohwM(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda31.run(R8$$SyntheticClass:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.replaceQueueIfUserConfirms(VideoDetailFragment.java:2124)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayer(VideoDetailFragment.java:1122)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayerAutoFullscreen(VideoDetailFragment.java:1135)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$32(VideoDetailFragment.java:875)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$gynX9IpWcI15Mq7luqpy5pBNIug(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda33.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	... 6 more

```
</details>
<hr>

**Comment by av01d1ngx4** [comment]
@Douile The error seems to have originated from the `PlayerService` of the `org.schabi.newpipe` package. It is possible that the service is taking too long to start and the Android system is timing out the request.

**Comment by fsudolphin** [comment]
> Did _anyone_ of you actually try to uninstall/reinstall?

Yes, but it's widespread and shouldn't be necessary to wipe out your config and rebuild it to avoid this behavior. It didn't work for me or apparently most anyone else anyway.

**Comment by badgooner** [comment]
Pixel 7
Start new pipe 
Go to pop up mode
Video plays normally with the app is not responding window

App version 0.25.1

**Comment by blauertee** [comment]
I recorded some logcat data can anyone tell me what to look for when removing personal information. It's just a vast amount of Output. I tried to only log NewPipes output but when filtering by PID there is just nothing suspicious. So I guess, I have to give you all the verbose spam my phone produces.

And maybe the title should be changed to include that this only seems to occur on pixel phones? At least I'm on a Pixel as well.

**Comment by kj** [comment]
@blauertee It's definitely not just Pixel phones. It also happens on my OnePlus 8 with LineageOS 20. There was a time a few months ago maybe where it was happening on nearly every video I opened (I might have been on an older version of LineageOS back then too). It's far less frequent now but it does still come up occasionally and I have to restart the app.

**Comment by blauertee** [comment]
Okay managed to isolate the relevant lines.

PID: 7460 is NewPipe heer :)

### The Output always generated hen "Not Responding" pops up:
```
06-26 14:03:21.945  1793  2172 D CoreBackPreview: Window{744d57b u0 Application Not Responding: org.schabi.newpipe}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@fb36f62, mPriority=0}
06-26 14:03:21.973  1793  7460 E OpenGLRenderer: Unable to match the desired swap behavior.
06-26 14:03:22.019  1793  7460 W Parcel  : Expecting binder but got null!
```


### When I press Close on the popup:
```
06-26 14:03:26.338  1058  6951 D C2BqBuffer: cannot dequeue buffer 0
06-26 14:03:26.338  1058  6951 E QC2Buf  : allocate: failed to alloc graphic block w(1280)/h(720)/f(7fa30c06)/usage(30010000)
06-26 14:03:26.339  1402 27949 D BufferPoolAccessor2.0: bufferpool2 0xb400007605c41ff8 : 4(16384 size) total buffers - 0(0 size) used buffers - 3023/3030 (recycle/alloc) - 17/3030 (fetch/transfer)
06-26 14:03:26.339  1793  2907 D MediaSessionService: Media button session is changed to null
06-26 14:03:26.340   998 11586 D msm8974_platform: platform_set_channel_map mixer_ctl_name:Playback Channel Map9
06-26 14:03:26.340   998 11586 D msm8974_platform: platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
06-26 14:03:26.340  1793  5028 I WindowManager: WIN DEATH: Window{868fc16 u0 org.schabi.newpipe/org.schabi.newpipe.MainActivity}
06-26 14:03:26.341   991   991 I Zygote  : Process 4580 exited due to signal 9 (Killed)
06-26 14:03:26.341  1793  5028 W InputManager-JNI: Input channel object '868fc16 org.schabi.newpipe/org.schabi.newpipe.MainActivity (client)' was disposed without first being removed with the input manager!
06-26 14:03:26.345 27793 27793 I MediaPlayerList: onMediaKeyEventSessionChanged: packageName=org.schabi.newpipe
06-26 14:03:26.348 27793 27793 W MediaPlayerList: org.schabi.newpipe is already the active player
06-26 14:03:26.348 27793 27793 V MediaPlayerList: onActiveSessionsChanged: number of controllers: 0
06-26 14:03:26.348 27793 27793 W AudioMediaPlayerWrapper: The session was destroyed org.schabi.newpipe
06-26 14:03:26.349  1058  6951 W QC2V4l2Codec: [avcD_227] Graphic output-buf allocation failed!
06-26 14:03:26.349  1058  6951 E QC2V4l2Codec: [avcD_227] Error during buffer allocation
06-26 14:03:26.350  1058  6951 D C2BqBuffer: cannot dequeue buffer 0
06-26 14:03:26.350  1058  6947 E QC2Comp : [avcD_227][ERROR] entered
06-26 14:03:26.350  1058  6951 E QC2Buf  : allocate: failed to alloc graphic block w(1280)/h(720)/f(7fa30c06)/usage(30010000)
06-26 14:03:26.350  1058  6951 W QC2V4l2Codec: [avcD_227] Graphic output-buf allocation failed!
06-26 14:03:26.350  1058  6951 E QC2V4l2Codec: [avcD_227] Error during buffer allocation
06-26 14:03:26.350  1058  6951 D C2BqBuffer: cannot dequeue buffer 0
06-26 14:03:26.350  1058  6951 E QC2Buf  : allocate: failed to alloc graphic block w(1280)/h(720)/f(7fa30c06)/usage(30010000)
06-26 14:03:26.350  1058  6951 W QC2V4l2Codec: [avcD_227] Graphic output-buf allocation failed!
06-26 14:03:26.350  1058  6951 E QC2V4l2Codec: [avcD_227] Error during buffer allocation
06-26 14:03:26.350  1058  6951 D C2BqBuffer: cannot dequeue buffer 0
```
The last three lines repeat for some more time.

**Comment by AudricV** [comment]
Logcat logs doesn't seem to be useful for us. We need ANRs traces, which you can probably get on Android Studio using the profiler. Analysis of these ANRs would higly appreciated, as we are not able to identify precisely from where the issue comes from.

**Comment by blauertee** [comment]
@AudricV Alright here you are :)
[anr_newpipe.txt](https://github.com/TeamNewPipe/NewPipe/files/11869432/anr_newpipe.txt)

**Comment by AudricV** [comment]
I don't see anything useful in the file you sent. Thanks anyway.

**Comment by blauertee** [comment]
Hmm sad tell me if you need anything else. This makes using the App really annoying. Oh and I forgot to include this from the ANR log:

```
--- CriticalEventLog ---
capacity: 20
events <
  timestamp_ms: 1687774577191
  anr <
    pid: 21685
    process: "org.schabi.newpipe"
    process_class: 1
    subject: "Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3e712ce u0 org.schabi.newpipe/.player.PlayerService}"
    uid: 10351
  >
>
timestamp_ms: 1687774651595
window_ms: 300000
```

**Comment by blauertee** [comment]
Probably this is not news to anyone here, but just in case (everybody missed the obvious sometimes). The Google [Diagnosing ANRs FAQ](https://developer.android.com/topic/performance/vitals/anr#diagnose-anrs) says:
- The main thread is doing a synchronous binder call to another process, and that other process is taking a long time to return.
This seems to be coherent with the logcat data where a binder is expected but null received. I don't know any of the context but maybe there is a simple way to do this async. or to lower the timeout and handle null, so the UI is not blocked for so long? In case you even know which call is blocking the UI here.

**Comment by FrostKiwi** [comment]
Still happening constantly. Here is another symptom: When the `not responding` + `wait` loop starts, you can close the app in the android app drawer and the message still pops up.
Like here in the video: I clicked Wait the first time, closed newpipe in the app drawer and the message still appears.

https://github.com/TeamNewPipe/NewPipe/assets/60887273/4d60a53f-be32-4e2c-ae86-0376dfc8c04f

**Comment by 32423d** [comment]
This issue still persists on v0.25.2. My device has not changed since this issue was created (Android 13 stable, Pixel 5a). Since the app works fine and the issue is that is just that the system error message is obscuring the screen I think a temporary solution would be to have an option in the app settings that prevents the app from making the system create error messages for it.

**Comment by 32423d** [comment]
> I managed to fix the issue, but i'm not sure if it's the real cause... after i cleared all downloads from the list (i never did since a year of usage, it was pretty large), no more popups. Updated to version 0.25.2

Is your device also on android 13 stable?

**Comment by kj** [comment]
I have nothing in my downloads list and I still see this after watching a few videos (it's usually okay if I only watch one or two). LineageOS 20 (Android 13).

**Comment by 32423d** [comment]
It seems clearing my download history did not fix this issue. I also cleared the cache and did a reinstall and loaded by save file back into the app but this did not resolve this issue either.

**Comment by Douile** [comment]
My theory is that the issue is caused by a large database causing some query that blocks startForegroundService to take too long.

I think this because if i remember correctly someone solved it for themselves by clearing the database, and it was solved for major by deleting a large amount of downloads.

Maybe we should try and get a flamegraph captured by someone experiencing the issue. I will look into getting one but i have a hard time replicating the issue on debug builds for some reason.

**Comment by FrostKiwi** [comment]
> It seems clearing my download history did not fix this issue. I also cleared the cache, did a reinstall, and loaded my save file back into the app but this did not resolve this issue either.

Can confirm this on my Pixel 6 Pro. Clearing download History does not solve the infinite wait loop.

**Comment by AudricV** [comment]
I think I found the origin of the presence of this Application Not Responding issue, could you look at https://github.com/TeamNewPipe/NewPipe/issues/9358#issuecomment-1722546621 and test the debug APK linked to see if the issue is fixed? Thanks in advance.

**Comment by kj** [comment]
> I think I found the origin of the presence of this Application Not Responding issue, could you look at https://github.com/TeamNewPipe/NewPipe/issues/9358#issuecomment-1722546621 and test the debug APK linked to see if the issue is fixed? Thanks in advance.

Thanks @AudricV, I've been through a few videos with the debug version and so far no issues (although of course it's not always consistent). I'll report back if this comes up for me again, but so far so good.

**Comment by FrostKiwi** [comment]
@AudricV I have also tested the https://github.com/TeamNewPipe/NewPipe/issues/9390 fix for a day now and same as @kj, have not observed a single hang, whereas I would have expected several yesterday.
So for me it's a clear 🎉 and I would consider this solved, once this hits the main release build.

Really awesome work fixing this one, I was slowly but surely losing my sanity.

**Comment by FrostKiwi** [comment]
Ahhhhhh bloddy hell.
Still got it once. But the frequency has most certainly decreased! Once per two days definitely better than 5 times a day...
https://github.com/TeamNewPipe/NewPipe/assets/60887273/776bf301-0d5c-4643-af99-38995e989108

**Comment by Rich700000000000** [comment]
I have no new code to add at this time, however, I've also experienced this bug. It seems most prevalent whenever I'm trying to download the audio from a video.

**Comment by FrostKiwi** [comment]
@AudricV
> could you look at [#9358 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/9358#issuecomment-1722546621) and test the debug APK linked to see if the issue is fixed?

Ohh noooooo, it happened again 😭

https://github.com/TeamNewPipe/NewPipe/assets/60887273/24dfa095-50fc-4cbb-8f08-c0f1f81f2f12

But the frequency of occurrence lower I think? Maybe a placebo? Either way, gonna try it out for a bit longer before coming to a definitive conclusion.
If I catch it again doing that thing, should I connect to the PC and pull an adb log cat while it's doing that loop stuck or something?

**Comment by kj** [comment]
It does seem less frequent at the very least. I still haven't run into it yet with this version, but it sounds like I may have just been lucky so far. I will definitely update if it does show up again for me too.

**Comment by kj** [comment]
Okay I finally ran into this again for the first time since installing the debug version. Still, it feels like a big improvement.

**Comment by kgutman-jpg** [comment]
Can you show me a screenshot with the popup while watching an episode of Wonderblocks on YouTube?
